-- Just rename some Blizzard keybindings to match the UI Layout
-- Maybe one day we will add something on mouseover

local T, C, L = select(2, ...):unpack()

local TukuiActionBars = T["ActionBars"]

function TukuiActionBars:Bindings()
	BINDING_NAME_ACTIONBUTTON1 = L.ActionBars.ActionButton1
	BINDING_NAME_ACTIONBUTTON2 = L.ActionBars.ActionButton2
	BINDING_NAME_ACTIONBUTTON3 = L.ActionBars.ActionButton3
	BINDING_NAME_ACTIONBUTTON4 = L.ActionBars.ActionButton4
	BINDING_NAME_ACTIONBUTTON5 = L.ActionBars.ActionButton5
	BINDING_NAME_ACTIONBUTTON6 = L.ActionBars.ActionButton6
	BINDING_NAME_ACTIONBUTTON7 = L.ActionBars.ActionButton7
	BINDING_NAME_ACTIONBUTTON8 = L.ActionBars.ActionButton8
	BINDING_NAME_ACTIONBUTTON9 = L.ActionBars.ActionButton9
	BINDING_NAME_ACTIONBUTTON10 = L.ActionBars.ActionButton10
	BINDING_NAME_ACTIONBUTTON11 = L.ActionBars.ActionButton11
	BINDING_NAME_ACTIONBUTTON12 = L.ActionBars.ActionButton12

	BINDING_NAME_MULTIACTIONBAR1BUTTON1 = L.ActionBars.MultiActionBar1Button1
	BINDING_NAME_MULTIACTIONBAR1BUTTON2 = L.ActionBars.MultiActionBar1Button2
	BINDING_NAME_MULTIACTIONBAR1BUTTON3 = L.ActionBars.MultiActionBar1Button3
	BINDING_NAME_MULTIACTIONBAR1BUTTON4 = L.ActionBars.MultiActionBar1Button4
	BINDING_NAME_MULTIACTIONBAR1BUTTON5 = L.ActionBars.MultiActionBar1Button5
	BINDING_NAME_MULTIACTIONBAR1BUTTON6 = L.ActionBars.MultiActionBar1Button6
	BINDING_NAME_MULTIACTIONBAR1BUTTON7 = L.ActionBars.MultiActionBar1Button7
	BINDING_NAME_MULTIACTIONBAR1BUTTON8 = L.ActionBars.MultiActionBar1Button8
	BINDING_NAME_MULTIACTIONBAR1BUTTON9 = L.ActionBars.MultiActionBar1Button9
	BINDING_NAME_MULTIACTIONBAR1BUTTON10 = L.ActionBars.MultiActionBar1Button10
	BINDING_NAME_MULTIACTIONBAR1BUTTON11 = L.ActionBars.MultiActionBar1Button11
	BINDING_NAME_MULTIACTIONBAR1BUTTON12 = L.ActionBars.MultiActionBar1Button12
	
	BINDING_NAME_MULTIACTIONBAR2BUTTON1 = L.ActionBars.MultiActionBar2Button1
	BINDING_NAME_MULTIACTIONBAR2BUTTON2 = L.ActionBars.MultiActionBar2Button2
	BINDING_NAME_MULTIACTIONBAR2BUTTON3 = L.ActionBars.MultiActionBar2Button3
	BINDING_NAME_MULTIACTIONBAR2BUTTON4 = L.ActionBars.MultiActionBar2Button4
	BINDING_NAME_MULTIACTIONBAR2BUTTON5 = L.ActionBars.MultiActionBar2Button5
	BINDING_NAME_MULTIACTIONBAR2BUTTON6 = L.ActionBars.MultiActionBar2Button6
	BINDING_NAME_MULTIACTIONBAR2BUTTON7 = L.ActionBars.MultiActionBar2Button7
	BINDING_NAME_MULTIACTIONBAR2BUTTON8 = L.ActionBars.MultiActionBar2Button8
	BINDING_NAME_MULTIACTIONBAR2BUTTON9 = L.ActionBars.MultiActionBar2Button9
	BINDING_NAME_MULTIACTIONBAR2BUTTON10 = L.ActionBars.MultiActionBar2Button10
	BINDING_NAME_MULTIACTIONBAR2BUTTON11 = L.ActionBars.MultiActionBar2Button11
	BINDING_NAME_MULTIACTIONBAR2BUTTON12 = L.ActionBars.MultiActionBar2Button12
	
	BINDING_NAME_MULTIACTIONBAR4BUTTON1 = BINDING_NAME_MULTIACTIONBAR3BUTTON1
	BINDING_NAME_MULTIACTIONBAR4BUTTON2 = BINDING_NAME_MULTIACTIONBAR3BUTTON2
	BINDING_NAME_MULTIACTIONBAR4BUTTON3 = BINDING_NAME_MULTIACTIONBAR3BUTTON3
	BINDING_NAME_MULTIACTIONBAR4BUTTON4 = BINDING_NAME_MULTIACTIONBAR3BUTTON4
	BINDING_NAME_MULTIACTIONBAR4BUTTON5 = BINDING_NAME_MULTIACTIONBAR3BUTTON5
	BINDING_NAME_MULTIACTIONBAR4BUTTON6 = BINDING_NAME_MULTIACTIONBAR3BUTTON6
	BINDING_NAME_MULTIACTIONBAR4BUTTON7 = BINDING_NAME_MULTIACTIONBAR3BUTTON7
	BINDING_NAME_MULTIACTIONBAR4BUTTON8 = BINDING_NAME_MULTIACTIONBAR3BUTTON8
	BINDING_NAME_MULTIACTIONBAR4BUTTON9 = BINDING_NAME_MULTIACTIONBAR3BUTTON9
	BINDING_NAME_MULTIACTIONBAR4BUTTON10 = BINDING_NAME_MULTIACTIONBAR3BUTTON10
	BINDING_NAME_MULTIACTIONBAR4BUTTON11 = BINDING_NAME_MULTIACTIONBAR3BUTTON11
	BINDING_NAME_MULTIACTIONBAR4BUTTON12 = BINDING_NAME_MULTIACTIONBAR3BUTTON12
	
	BINDING_NAME_MULTIACTIONBAR3BUTTON1 = L.ActionBars.MultiActionBar4Button1
	BINDING_NAME_MULTIACTIONBAR3BUTTON2 = L.ActionBars.MultiActionBar4Button2
	BINDING_NAME_MULTIACTIONBAR3BUTTON3 = L.ActionBars.MultiActionBar4Button3
	BINDING_NAME_MULTIACTIONBAR3BUTTON4 = L.ActionBars.MultiActionBar4Button4
	BINDING_NAME_MULTIACTIONBAR3BUTTON5 = L.ActionBars.MultiActionBar4Button5
	BINDING_NAME_MULTIACTIONBAR3BUTTON6 = L.ActionBars.MultiActionBar4Button6
	BINDING_NAME_MULTIACTIONBAR3BUTTON7 = L.ActionBars.MultiActionBar4Button7
	BINDING_NAME_MULTIACTIONBAR3BUTTON8 = L.ActionBars.MultiActionBar4Button8
	BINDING_NAME_MULTIACTIONBAR3BUTTON9 = L.ActionBars.MultiActionBar4Button9
	BINDING_NAME_MULTIACTIONBAR3BUTTON10 = L.ActionBars.MultiActionBar4Button10
	BINDING_NAME_MULTIACTIONBAR3BUTTON11 = L.ActionBars.MultiActionBar4Button11
	BINDING_NAME_MULTIACTIONBAR3BUTTON12 = L.ActionBars.MultiActionBar4Button12
end

