if GetLocale() == "zhCN" then
	--Translated by 风吹那啥凉 （Popptise @Tukui forums)
    --Translated by guo2easy (guo2easy@bbs.ngacn.cc)
	-- general
	TukuiConfigUILocalization.general = "综合"
	TukuiConfigUILocalization.generalautoscale = "UI自动缩放"
	TukuiConfigUILocalization.generaloverridelowtohigh = "在低分辨率下使用高分辨率样式"
	TukuiConfigUILocalization.generalmultisampleprotect = "多重采样保护 (修复1像素的边框)"
	TukuiConfigUILocalization.generaluiscale = "UI缩放 (仅在UI自动缩放关闭的时候启用)"
	TukuiConfigUILocalization.generalbackdropcolor = "设置默认的面板背景色"
	TukuiConfigUILocalization.generalbordercolor = "设置默认的面板边框颜色"
	TukuiConfigUILocalization.generalblizzardreskin = "改变暴雪样式的框体为Tukui风格"
	 
	-- nameplate
	TukuiConfigUILocalization.nameplate = "姓名版"
	TukuiConfigUILocalization.nameplateenable = "开启姓名版"
	TukuiConfigUILocalization.nameplateenhancethreat = "启用仇恨着色模式，将会根据你的角色自动改变颜色"
	TukuiConfigUILocalization.nameplateshowhealth = "在姓名板上显示生命值"
	TukuiConfigUILocalization.nameplatecombat = "仅在战斗中显示姓名板"
	TukuiConfigUILocalization.nameplategoodcolor = "安全仇恨值颜色，取决于你是坦克还是治疗者"
	TukuiConfigUILocalization.nameplatebadcolor = "危险仇恨值颜色，取决于你是治疗还是输出"
	TukuiConfigUILocalization.nameplatetransitioncolor = "失去/获得仇恨值颜色"
	 
	-- merchant
	TukuiConfigUILocalization.merchant = "商人"
	TukuiConfigUILocalization.merchantsellgrays = "自动售卖灰色物品"
	TukuiConfigUILocalization.merchantautorepair = "自动修理物品"
	TukuiConfigUILocalization.merchantsellmisc = "自动贩卖特定物品(非灰色等级的指定物品)"
	 
	-- bags
	TukuiConfigUILocalization.bags = "背包"
	TukuiConfigUILocalization.bagsenable = "开启背包整合"
	 
	-- datatext
	TukuiConfigUILocalization.datatext = "文本信息"
	TukuiConfigUILocalization.datatexttime24 = "使用24小时制"
	TukuiConfigUILocalization.datatextlocaltime = "使用本地时间取代服务器时间"
	TukuiConfigUILocalization.datatextbattleground = "启用战场状态"
	TukuiConfigUILocalization.datatexthps_text = "每秒治疗(输入0关闭)"
	TukuiConfigUILocalization.datatextguild = "公会信息 (输入0关闭)"
	TukuiConfigUILocalization.datatext_arp = "护甲穿透 (输入0关闭)"
	TukuiConfigUILocalization.datatextsystem = "内存占用信息 (输入0关闭)"
	TukuiConfigUILocalization.datatextbags = "背包 (输入0关闭)"
	TukuiConfigUILocalization.datatextfontsize = "文本字体大小"
	TukuiConfigUILocalization.datatextfps_ms = "延时和帧数(输入0关闭)"
	TukuiConfigUILocalization.datatextarmor = "护甲值 (输入0关闭)"
	TukuiConfigUILocalization.datatextavd = "免伤 (输入0关闭)"
	TukuiConfigUILocalization.datatextpower = "攻强/法伤(输入0关闭)"
	TukuiConfigUILocalization.datatexthaste = "急速(输入0关闭)"
	TukuiConfigUILocalization.datatextfriends = "好友(输入0关闭)"
	TukuiConfigUILocalization.datatextwowtime = "时间(输入0关闭)"
	TukuiConfigUILocalization.datatextgold = "金币(输入0关闭)"
	TukuiConfigUILocalization.datatextdps_text = "DPS (输入0关闭)"
	TukuiConfigUILocalization.datatextcrit = "爆击 % (输入0关闭)"
	TukuiConfigUILocalization.datatextdur = "耐久度(输入0关闭)"
	TukuiConfigUILocalization.datatextcurrency = "货币(输入0关闭)"
	TukuiConfigUILocalization.datatextmicromenu = "微型菜单(输入0关闭)"
	TukuiConfigUILocalization.datatexthit = "命中(输入0关闭)"
	TukuiConfigUILocalization.datatextmastery = "精通 (输入0关闭)"
	TukuiConfigUILocalization.datatexttalent = "显示天赋 (输入0关闭)"
	TukuiConfigUILocalization.datatextcalltoarms = "地下城战斗的召唤 (输入0关闭)"
	TukuiConfigUILocalization.datatextregen = MANA_REGEN_ABBR
	 
	-- unit frames
	TukuiConfigUILocalization.unitframes = "单位框体"
	TukuiConfigUILocalization.unitframesenable = "启用Tukui头像框架"
	TukuiConfigUILocalization.unitframescombatfeedback = "在玩家和目标框体上显示战斗信息"
	TukuiConfigUILocalization.unitframesrunebar = "启用死亡骑士符文条"
	TukuiConfigUILocalization.unitframesauratimer = "在光环上显示时间"
	TukuiConfigUILocalization.unitframestotembar = "启用萨满图腾条"
	TukuiConfigUILocalization.unitframesshowtotalhpmp = "显示总的生命/能量值"
	TukuiConfigUILocalization.unitframesshowplayerinparty = "在团队中显示你自己"
	TukuiConfigUILocalization.unitframesraidunitdebuffwatch = "启用PVE光环检测 (只能在GRIG模式下)"
	TukuiConfigUILocalization.unitframesunitcastbar = "启用施法条"
	TukuiConfigUILocalization.unitframestargetauras = "启用目标光环"
	TukuiConfigUILocalization.unitframessaveperchar = "为每个角色单独存储框架位置"
	TukuiConfigUILocalization.unitframesplayeraggro = "在自身头像上启用仇恨显示"
	TukuiConfigUILocalization.unitframesshowsmooth = "启用平滑状态条"
	TukuiConfigUILocalization.unitframescharportrait = "为自身和目标启用头像显示"
	TukuiConfigUILocalization.unitframestargetpowerpvponly = "只显示敌对目标的能量值"
	TukuiConfigUILocalization.unitframesgridonly = "治疗模式下仅使用GRID样式"
	TukuiConfigUILocalization.unitframeshealcomm = "启用预估治疗"
	TukuiConfigUILocalization.unitframesfocusdebuff = "启用焦点DEBUFF"
	TukuiConfigUILocalization.unitframesaggro = "在小队/团队中启用仇恨显示"
	TukuiConfigUILocalization.unitframesshowboss = "启用BOSS框体"
	TukuiConfigUILocalization.unitframesenemyhcolor = "用敌对颜色为敌人框体着色 (仅 PVP)"
	TukuiConfigUILocalization.unitframesgridhealthvertical = "在Grid模式中垂直显示生命条"
	TukuiConfigUILocalization.unitframesshowsymbols = "显示小队/团队标记"
	TukuiConfigUILocalization.unitframesthreatbar = "启用仇恨条"
	TukuiConfigUILocalization.unitframesshowrange = "启用小队/团队距离检测"
	TukuiConfigUILocalization.unitframesfocus = "启用焦点框体"
	TukuiConfigUILocalization.unitframesshowfocustarget = "启用焦点的目标框体"
	TukuiConfigUILocalization.unitframescblatency = "显示施法延时"
	TukuiConfigUILocalization.unitframescbicons = "显示施法条图标"
	TukuiConfigUILocalization.unitframesplayerauras = "为玩家启用额外的光环模式"
	TukuiConfigUILocalization.unitframesauratextscale = "光环文字大小设置"
	TukuiConfigUILocalization.unitframesgridscale = "Grid框体大小"
	TukuiConfigUILocalization.unitframesmanahigh = "法力值过高警报 (LR专用)"
	TukuiConfigUILocalization.unitframeslowThreshold = "低法力值警报 (所有的法系职业)"
	TukuiConfigUILocalization.unitframesraidalphaoor = "小队/团队超出距离透明值"
	TukuiConfigUILocalization.unitframesmaintank = "启用主坦克框体"
	TukuiConfigUILocalization.unitframesmainassist = "启用主助理框架"
	TukuiConfigUILocalization.unitframesunicolor = "启用单一的颜色主题(灰色的生命条)"
	TukuiConfigUILocalization.unitframestotdebuffs = "启用目标的目标的DEBUFF显示 (仅限高分辨率)"
	TukuiConfigUILocalization.unitframesclassbar = "启用职业条"
	TukuiConfigUILocalization.unitframesweakenedsoulbar = "启用灵魂虚弱指示 (牧师)"
	TukuiConfigUILocalization.unitframesonlyselfdebuffs = "只在目标框体上显示你释放的DEBUFF"
	TukuiConfigUILocalization.unitframesbordercolor = "设置为默认的边框颜色"
	TukuiConfigUILocalization.unitframesraid = "启用Tukui团队框架"
	TukuiConfigUILocalization.unitframesshowraidpets = "团队框架中启用宠物框体"
	TukuiConfigUILocalization.unitframesdruidmanabar = "熊、猫姿态下显示魔法条（德鲁伊）"
	TukuiConfigUILocalization.unitframesdruidmushroombar = "平衡或恢复天赋下启用蘑菇条（德鲁伊）"
	TukuiConfigUILocalization.unitframesmageclassbar = "启用奥法助手"
	TukuiConfigUILocalization.unitframesraidunitspercolumn = "团队框架中每行/列的单位数量"
	TukuiConfigUILocalization.unitframesmovecombobar = "将能量条移动至目标框体 (仅潜行者)"
	TukuiConfigUILocalization.unitframesclassiccombo = "使用经典连击点样式"
	TukuiConfigUILocalization.unitframesgridvertical = "在Grid中垂直显示小队"
	TukuiConfigUILocalization.unitframesmaxraidplayers = "根据最大玩家人数调整团队框架"
	TukuiConfigUILocalization.unitframesshowstatuebar = "显示状态条（职业条必须开启的情况下）"
	 
	-- loot
	TukuiConfigUILocalization.loot = "拾取"
	TukuiConfigUILocalization.lootlootframe = "启用拾取框"
	TukuiConfigUILocalization.lootautogreed = "满级时启用自动贪婪绿色物品"
	TukuiConfigUILocalization.lootrolllootframe = "启用Roll点框体"
	 
	-- invite
	TukuiConfigUILocalization.invite = "邀请"
	TukuiConfigUILocalization.inviteautoaccept = "开启自动接受邀请 (好友和公会成员)"
	 
	-- tooltip
	TukuiConfigUILocalization.tooltip = "鼠标提示"
	TukuiConfigUILocalization.tooltipenable = "开启鼠标提示"
	TukuiConfigUILocalization.tooltiphidecombat = "战斗中隐藏鼠标提示"
	TukuiConfigUILocalization.tooltiphidebuttons = "隐藏动作条鼠标提示"
	TukuiConfigUILocalization.tooltiphideuf = "隐藏头像框体鼠标提示"
	TukuiConfigUILocalization.tooltipcursor = "开启提示跟随鼠标指针"
	 
	-- error
	TukuiConfigUILocalization.error = "错误信息"
	TukuiConfigUILocalization.errorenable = "隐藏屏幕中间的红色错误提示信息"
	 
	-- action bar
	TukuiConfigUILocalization.actionbar = "动作条"
	TukuiConfigUILocalization.actionbarhideshapeshift = "隐藏姿态或者图腾栏"
	TukuiConfigUILocalization.actionbarshowgrid = "始终在动作条上显示空按钮"
	TukuiConfigUILocalization.actionbarenable = "启用Tukui动作条"
	TukuiConfigUILocalization.actionbarrb = "启用右侧动作条鼠标划过显示"
	TukuiConfigUILocalization.actionbarhotkey = "显示快捷键名称"
	TukuiConfigUILocalization.actionbarssmo = "鼠标划过显示姿态栏和图腾栏"
	TukuiConfigUILocalization.actionbarrbn = "底部动作条数目 (1 或 2)"
	TukuiConfigUILocalization.actionbarrn = "右侧动作条数目 (0, 1, 2 或 3)"
	TukuiConfigUILocalization.actionbarbuttonsize = "主动作条按钮大小"
	TukuiConfigUILocalization.actionbarbuttonspacing = "动作条按钮间距"
	TukuiConfigUILocalization.actionbarpetbuttonsize = "宠物或姿态栏按钮大小"
	TukuiConfigUILocalization.actionbarownshdbar = "当暗影之舞时使用一个空的动作条来替代盗贼的潜行动作条（仅盗贼）"
	TukuiConfigUILocalization.actionbarownmetabar = "当恶魔形态时使用一个空的动作条来替代主动作条（仅术士）"
	TukuiConfigUILocalization.actionbarownwarstancebar = "切换姿态时使用一个空的动作条来替代主动作条（仅战士）"
	TukuiConfigUILocalization.actionbarmacro = "在动作条上显示宏名称"
	 
	-- arena
	TukuiConfigUILocalization.arena = "竞技场"
	TukuiConfigUILocalization.unitframesarena = "开启竞技场单位框体"
	 
	-- cooldowns
	TukuiConfigUILocalization.cooldown = "冷却"
	TukuiConfigUILocalization.cooldownenable = "在按钮上显示冷却时间"
	TukuiConfigUILocalization.cooldowntreshold = "在X秒以后以红色显示冷却时间"
	 
	-- chat
	TukuiConfigUILocalization.chat = "聊天"
	TukuiConfigUILocalization.chatenable = "启用Tukui的聊天框架"
	TukuiConfigUILocalization.chatwhispersound = "在收到密语时播放提示音"
	TukuiConfigUILocalization.chatbackground = "启用聊天面板背景"

	-- buff
	TukuiConfigUILocalization.auras = "光环"
	TukuiConfigUILocalization.aurasplayer = "启用Tukui Buff/Debuff 框架"
	TukuiConfigUILocalization.aurasconsolidate = "启用BUFF整合"
	TukuiConfigUILocalization.aurasflash = "当光环剩余时间少于30秒时启用闪烁动画"
	TukuiConfigUILocalization.aurasclassictimer = "启用经典光环计时"


	-- buttons
	TukuiConfigUILocalization.option_button_reset = "重置"
	TukuiConfigUILocalization.option_button_load = "应用设定"
	TukuiConfigUILocalization.option_button_close = "关闭"
	TukuiConfigUILocalization.option_setsavedsetttings = "为每个角色设定"
	TukuiConfigUILocalization.option_resetchar = "你确定要重置这个角色的设定到你的默认设定么?"
	TukuiConfigUILocalization.option_resetall = "你确定要重置角色的设置为默认值么?"
	TukuiConfigUILocalization.option_perchar = "你确定要启用或者关闭“为单一角色设定”么?"
	TukuiConfigUILocalization.option_makeselection = "在你继续设置之前你必须要做出一个选择。"
end
