if GetLocale() == "frFR" then
	-- translated by Spyritus <3

	-- general
	TukuiConfigUILocalization.general = "Général"
	TukuiConfigUILocalization.generalautoscale = "Échelle de l'interface automatique"
	TukuiConfigUILocalization.generaloverridelowtohigh = "Utiliser la disposition haute résolution en basse résolution"
	TukuiConfigUILocalization.generalmultisampleprotect = "Protection multi-échantillonnage (bords 1px nets)"
	TukuiConfigUILocalization.generaluiscale = "Échelle de l'interface (si l'échelle automatique est désactivée)"
	TukuiConfigUILocalization.generalbackdropcolor = "Définir la couleur par défaut de fond des panneaux"
	TukuiConfigUILocalization.generalbordercolor = "Définir la couleur par défaut des bords des panneaux"
	TukuiConfigUILocalization.generalblizzardreskin = "Appliquer le thème Tukui aux fenêtre de Blizzard"
	 
	-- nameplate
	TukuiConfigUILocalization.nameplate = "Barres d'info"
	TukuiConfigUILocalization.nameplateenable = "Activer les barres d'info"
	TukuiConfigUILocalization.nameplateenhancethreat = "Activer le système de menace, change automatiquement selon votre rôle"
	TukuiConfigUILocalization.nameplateshowhealth = "Montrer la santé sur les barres d'info"
	TukuiConfigUILocalization.nameplatecombat = "Afficher les barres d'infos des ennemis seulement en combat"
	TukuiConfigUILocalization.nameplategoodcolor = "Couleur de menace faible, dépend du rôle, tank ou dps/soins"
	TukuiConfigUILocalization.nameplatebadcolor = "Couleur de menace élevée, dépend du rôle, tank ou dps/soins"
	TukuiConfigUILocalization.nameplatetransitioncolor = "Couleur de perte/Gain de menace"
	 
	-- merchant
	TukuiConfigUILocalization.merchant = "Marchand"
	TukuiConfigUILocalization.merchantsellgrays = "Vendre automatiquement les objets gris"
	TukuiConfigUILocalization.merchantautorepair = "Réparer automatiquement"
	TukuiConfigUILocalization.merchantsellmisc = "Vendre automatiquement des objets définis (autre que gris)"
	 
	-- bags
	TukuiConfigUILocalization.bags = "Sacs"
	TukuiConfigUILocalization.bagsenable = "Activer le sac tout-en-un"
	 
	-- datatext
	TukuiConfigUILocalization.datatext = "Texte d'info"
	TukuiConfigUILocalization.datatexttime24 = "Afficher l'heure au format 24h"
	TukuiConfigUILocalization.datatextlocaltime = "Utiliser l'heure locale au lieu de l'heure du serveur"
	TukuiConfigUILocalization.datatextbattleground = "Activer les statistiques des champs de bataille"
	TukuiConfigUILocalization.datatexthps_text = "Position du module soins par seconde (0 = désactivé)"
	TukuiConfigUILocalization.datatextguild = "Position du module Guilde (0 = désactivé)"
	TukuiConfigUILocalization.datatext_arp = "Position du score de Pénétration d'armure (0 = désactivé)"
	TukuiConfigUILocalization.datatextsystem = "Position du module Mémoire système (0 = désactivé)"
	TukuiConfigUILocalization.datatextbags = "Position du module Sacs (0 = désactivé)"
	TukuiConfigUILocalization.datatextfontsize = "Taille des textes"
	TukuiConfigUILocalization.datatextfps_ms = "Position du module Latence et IPS (0 = désactivé)"
	TukuiConfigUILocalization.datatextarmor = "Position du score d'armure (0 = désactivé)"
	TukuiConfigUILocalization.datatextavd = "Position du score d'esquive (0 = désactivé)"
	TukuiConfigUILocalization.datatextpower = "Position du score de Puissance d'Attaque/Sorts (0 = désactivé)"
	TukuiConfigUILocalization.datatexthaste = "Position du score de Hâte (0 = désactivé)"
	TukuiConfigUILocalization.datatextfriends = "Position du module Amis (0 = désactivé)"
	TukuiConfigUILocalization.datatextwowtime = "Position de l'Heure (0 = désactivé)"
	TukuiConfigUILocalization.datatextgold = "Position du module Richesse (0 = désactivé)"
	TukuiConfigUILocalization.datatextdps_text = "Position du module Dégâts par seconde (0 = désactivé)"
	TukuiConfigUILocalization.datatextcrit = "Position du % critique (0 = désactivé)"
	TukuiConfigUILocalization.datatextdur = "Position de la durabilité (0 = désactivé)"
	TukuiConfigUILocalization.datatextcurrency = "Position du module des monnaies (0 = désactivé)"
	TukuiConfigUILocalization.datatextmicromenu = "Position du micro menu (0 = désactivé)"
	TukuiConfigUILocalization.datatexthit = "Position du score de toucher (0 = désactivé)"
	TukuiConfigUILocalization.datatextmastery = "Position du score de maîtrise (0 = désactivé)"
	TukuiConfigUILocalization.datatexttalent = "Afficher les talents (0 = désactivé)"
	TukuiConfigUILocalization.datatextcalltoarms = "Appel aux armes & donjons (0 = désactivé)"
	TukuiConfigUILocalization.unitframesmovecombobar = "Déplacer la barre de combo de la cible (VOLEUR SEULEMENT)"
	TukuiConfigUILocalization.unitframesclassiccombo = "Utiliser les points de combo classiques"
	TukuiConfigUILocalization.unitframesgridvertical = "Afficher les groupes de raid Grid verticalement"

	 
	-- unit frames
	TukuiConfigUILocalization.unitframes = "Barres d'unités"
	TukuiConfigUILocalization.unitframescombatfeedback = "Indications de combat sur le joueur et sa cible"
	TukuiConfigUILocalization.unitframesrunebar = "Afficher la barre de runes (Chevaliers de la mort)"
	TukuiConfigUILocalization.unitframesauratimer = "Afficher le timer des améliorations/affaiblissements"
	TukuiConfigUILocalization.unitframestotembar = "Afficher la barre de totems (Chamans)"
	TukuiConfigUILocalization.unitframesshowtotalhpmp = "Afficher le total de vie/pouvoir(mana,rage,...)"
	TukuiConfigUILocalization.unitframesshowplayerinparty = "Se voir dans le groupe"
	TukuiConfigUILocalization.unitframesraidunitdebuffwatch = "Afficher les buffs PVE en raid (Grid seulement)"
	TukuiConfigUILocalization.unitframesunitcastbar = "Activer la barre d'incantation"
	TukuiConfigUILocalization.unitframestargetauras = "Afficher les améliorations/affaiblissements de la cible"
	TukuiConfigUILocalization.unitframessaveperchar = "Sauvegardes la position des cadres par personnage"
	TukuiConfigUILocalization.unitframesplayeraggro = "Afficher l'aggro sur soi"
	TukuiConfigUILocalization.unitframesshowsmooth = "Activer les animations des barres douces"
	TukuiConfigUILocalization.unitframescharportrait = "Afficher les portraits du joueur et de la cible"
	TukuiConfigUILocalization.unitframesenable = "Activer les barres d'unités Tukui"
	TukuiConfigUILocalization.unitframestargetpowerpvponly = "Afficher seulement le pouvoir (mana,rage,...) de l'ennemi"
	TukuiConfigUILocalization.unitframesgridonly = "Afficher seulement le mode Grid sur la disposition soigneur"
	TukuiConfigUILocalization.unitframeshealcomm = "Afficher soins reçus (sur les barres de vie)"
	TukuiConfigUILocalization.unitframesfocusdebuff = "Afficher les affaiblissements de la focalisation"
	TukuiConfigUILocalization.unitframesaggro = "Afficher l'aggro en groupe/raid"
	TukuiConfigUILocalization.unitframesshowboss = "Activer les barres d'unité des Boss"
	TukuiConfigUILocalization.unitframesenemyhcolor = "Colorer la barre de vie des ennemis par hostilité (PVP)"
	TukuiConfigUILocalization.unitframesgridhealthvertical = "Afficher la santé verticalement sur Grid"
	TukuiConfigUILocalization.unitframesshowsymbols = "Afficher les symboles en groupe/raid"
	TukuiConfigUILocalization.unitframesthreatbar = "Activer la barre de menace"
	TukuiConfigUILocalization.unitframesshowrange = "Afficher le groupe/raid transparent en fonction de la portée"
	TukuiConfigUILocalization.unitframesfocus = "Afficher la focalisation"
	TukuiConfigUILocalization.unitframescblatency = "Afficher la latence de la barre d'incantation"
	TukuiConfigUILocalization.unitframescbicons = "Afficher les icônes sur les barres d'incantation"
	TukuiConfigUILocalization.unitframesplayerauras = "Activer un mode amélioration/affaiblissement alternatif pour le joueur"
	TukuiConfigUILocalization.unitframesauratextscale = "Échelle du texte des améliorations/affaiblissements"
	TukuiConfigUILocalization.unitframesgridscale = "Échelle Grid"
	TukuiConfigUILocalization.unitframesmanahigh = "Indication de mana élevé (pour Chasseurs)"
	TukuiConfigUILocalization.unitframeslowThreshold = "Indication de mana faible (toutes classes à mana)"
	TukuiConfigUILocalization.unitframesraidalphaoor = "Transparence des joueurs en groupe/raid hors de portée"
	TukuiConfigUILocalization.unitframesmaintank = "Afficher Tank principal"
	TukuiConfigUILocalization.unitframesmainassist = "Afficher Assist principal"
	TukuiConfigUILocalization.unitframesunicolor = "Utiliser un thème de couleur unique (barre de vie grise)"
	TukuiConfigUILocalization.unitframestotdebuffs = "Afficher les affaiblissements de la cible de la cible (Haute réso.)"
	TukuiConfigUILocalization.unitframesclassbar = "Afficher la barre de classe"
	TukuiConfigUILocalization.unitframesweakenedsoulbar = "Activer la barre d'âme affaiblie (Prêtre)"
	TukuiConfigUILocalization.unitframesonlyselfdebuffs = "Afficher seulement vos affaiblissements sur la cible"
	TukuiConfigUILocalization.unitframesshowfocustarget = "Afficher la focalisation de la cible"
	TukuiConfigUILocalization.unitframesbordercolor = "Définir la couleur par défaut des bords des panneaux"
	TukuiConfigUILocalization.unitframesraid = "Activer l'interface de raid de Tukui"
	TukuiConfigUILocalization.unitframesshowraidpets = "Afficher les familiers dans l'interface de raid"
	TukuiConfigUILocalization.unitframesdruidmanabar = "Afficher la barre de mana des druides en forme de félin / ours"
	TukuiConfigUILocalization.unitframesdruidmushroombar = "Afficher la barre de champignons en spécialisation équilibre et restauration"
	TukuiConfigUILocalization.unitframesmageclassbar = "Afficher la barre d'arcane du mage."
	TukuiConfigUILocalization.unitframesraidunitspercolumn = "Nombre d'unités de raid par colonne / ligne"
	TukuiConfigUILocalization.unitframesmaxraidplayers = "Max raid frames displayed according to instance max players"
	 
	-- loot
	TukuiConfigUILocalization.loot = "Butin"
	TukuiConfigUILocalization.lootlootframe = "Activer la fenêtre de butin"
	TukuiConfigUILocalization.lootautogreed = "Cupidité automatique pour les objets verts au niveau maximum"
	TukuiConfigUILocalization.lootrolllootframe = "Activer la fenêtre d'attribution de butin"
	 
	-- invite
	TukuiConfigUILocalization.invite = "Invitation"
	TukuiConfigUILocalization.inviteautoaccept = "Accepter les invitations automatiquement (Amis et guilde)"
	 
	-- tooltip
	TukuiConfigUILocalization.tooltip = "Bulle d'info"
	TukuiConfigUILocalization.tooltipenable = "Activer la bulle d'info"
	TukuiConfigUILocalization.tooltiphidecombat = "Cacher la bulle d'info en combat"
	TukuiConfigUILocalization.tooltiphidebuttons = "Cacher la bulle d'info pour les boutons des barres d'action"
	TukuiConfigUILocalization.tooltiphideuf = "Cacher la bulle d'info pour les barres d'unités"
	TukuiConfigUILocalization.tooltipcursor = "Afficher la bulle d'info au niveau du curseur"
	 
	-- error
	TukuiConfigUILocalization.error = "Messages d'erreur"
	TukuiConfigUILocalization.errorenable = "Cacher les messages d'erreur apparaissant au milieu de l'écran"
	 
	-- action bar
	TukuiConfigUILocalization.actionbar = "Barres d'action"
	TukuiConfigUILocalization.actionbarhideshapeshift = "Cacher la barre de forme/totem"
	TukuiConfigUILocalization.actionbarshowgrid = "Toujours afficher la grille des barres d'action"
	TukuiConfigUILocalization.actionbarenable = "Activer les barres d'action Tukui"
	TukuiConfigUILocalization.actionbarrb = "Afficher la barre de droite au survol de la souris"
	TukuiConfigUILocalization.actionbarhotkey = "Afficher les raccourcis sur les boutons"
	TukuiConfigUILocalization.actionbarssmo = "Afficher la barre de formes/totems au survol de la souris"
	TukuiConfigUILocalization.actionbarrbn = "Nombre de barres d'action en bas (1 or 2)"
	TukuiConfigUILocalization.actionbarrn = "Nombre de barres d'actions à droite (0, 1, 2 or 3)"
	TukuiConfigUILocalization.actionbarbuttonsize = "Taille de la barre d'action principale"
	TukuiConfigUILocalization.actionbarbuttonspacing = "Espacement entre les boutons de la barre principale"
	TukuiConfigUILocalization.actionbarpetbuttonsize = "Taille des boutons de la barre de formes/du familier"
	TukuiConfigUILocalization.actionbarownshdbar = "Utiliser une barre vide pour 'Danse de l'ombre' (voleur) au lieu de la barre de camouflage"
	TukuiConfigUILocalization.actionbarownmetabar = "Utiliser une barre d'action vide pour Métamorphose (démoniste) au lieu de la barre principale"
	TukuiConfigUILocalization.actionbarownwarstancebar = "Utiliser une barre d'action vide pour chaque posture (guerrier) au lieu de la barre principale"
	TukuiConfigUILocalization.actionbarmacro = "Affiche le nom des macros sur la barre d'action"
	 
	-- arena
	TukuiConfigUILocalization.arena = "Arène"
	TukuiConfigUILocalization.unitframesarena = "Activer les barres d'unités en arène"
	 
	-- cooldowns
	TukuiConfigUILocalization.cooldown = "Comptes à rebours"
	TukuiConfigUILocalization.cooldownenable = "Afficher le compte à rebours sur les boutons"
	TukuiConfigUILocalization.cooldowntreshold = "Compte à rebours rouge sous la valeur X"
	 
	-- chat
	TukuiConfigUILocalization.chat = "Discussions"
	TukuiConfigUILocalization.chatenable = "Activer les fenêtres de discussion Tukui"
	TukuiConfigUILocalization.chatwhispersound = "Jouer un son à la réception des chuchotements"
	TukuiConfigUILocalization.chatbackground = "Afficher un fond derrière les fenêtres de discussion"

	-- buff
	TukuiConfigUILocalization.auras = "Améliorations/affaiblissements"
	TukuiConfigUILocalization.aurasplayer = "Activer les fenêtres d'amélioration/affaiblissement Tukui"
	TukuiConfigUILocalization.aurasconsolidate = "Regrouper des améliorations"
	TukuiConfigUILocalization.aurasflash = "Activer l'animation de flash lorsqu'il reste moins de 30 secondes"
	TukuiConfigUILocalization.aurasclassictimer = "Utiliser l'affichage classique pour la durée des auras du joueur"

	-- buttons
	TukuiConfigUILocalization.option_button_reset = "Réinitialiser"
	TukuiConfigUILocalization.option_button_load = "Appliquer les paramètres"
	TukuiConfigUILocalization.option_button_close = "Fermer"
	TukuiConfigUILocalization.option_setsavedsetttings = "Définir les paramètres par personnage"
	TukuiConfigUILocalization.option_resetchar = "Êtes-vous sûr de vouloir réinitialiser les paramètres de ce personnage?"
	TukuiConfigUILocalization.option_resetall = "Êtes-vous sûr de vouloir réinitialiser tous vos paramètres?"
	TukuiConfigUILocalization.option_perchar = "Êtes-vous sûr de vouloir basculer vers/de 'Paramètres par personnage'?"
	TukuiConfigUILocalization.option_makeselection = "Vous devez faire un choix avant de continuer."
end