if GetLocale() == "deDE" then
	-- translated by ?

	-- general
	TukuiConfigUILocalization.general = "Allgemein"
	TukuiConfigUILocalization.generalautoscale = "Nutze automatische UI-Skalierung"
	TukuiConfigUILocalization.generaloverridelowtohigh = "Nutze Layout für hohe auf niedriger Auflösung"
	TukuiConfigUILocalization.generalmultisampleprotect = "Multisampling Schutz (sauberer 1px Ränder)"
	TukuiConfigUILocalization.generaluiscale = "UI Skalierung (Wenn Autoskalierung deaktiviert ist)"
	TukuiConfigUILocalization.generalbackdropcolor = "Hintergrundfarbe der Panels"
	TukuiConfigUILocalization.generalbordercolor = "Randfarbe der Panels"
	TukuiConfigUILocalization.generalblizzardreskin = "Änder Blizzardframes so das sie Aussehen wie Tukui"
	TukuiConfigUILocalization.generalmultiplescreendamage = "Enable multiple monitors text damage (Surround/Eyefinity)"
	 
	-- nameplate
	TukuiConfigUILocalization.nameplate = "Namensplaketten"
	TukuiConfigUILocalization.nameplateenable = "Aktiviere Namensplaketten"
	TukuiConfigUILocalization.nameplateenhancethreat = "Aktiviere Bedrohungsanzeige, ändert sich automatisch nach Rolle"
	TukuiConfigUILocalization.nameplateshowhealth = "Zeige Leben an Namensplaketten"
	TukuiConfigUILocalization.nameplatecombat = "Zeige nur feindliche Namensplaketten im Kampf"
	TukuiConfigUILocalization.nameplategoodcolor = "Farbe für gute Bedrohung, hängt davon ab ob du Tank oder Heiler/DDler bist"
	TukuiConfigUILocalization.nameplatebadcolor = "Farbe für schlechte Bedrohung, hängt davon ab ob du Tank oder Heiler/DDler bist"
	TukuiConfigUILocalization.nameplatetransitioncolor = "Farbe für verlieren/erhalten von Bedrohnung"
	 
	-- merchant
	TukuiConfigUILocalization.merchant = "Händler"
	TukuiConfigUILocalization.merchantsellgrays = "Automatisch graue Gegenstände verkaufen"
	TukuiConfigUILocalization.merchantautorepair = "Automatisch alle Gegenstände reparieren"
	TukuiConfigUILocalization.merchantsellmisc = "Verkaufe vordefenierte (nutzlose, nicht graue) Gegenstände automatisch"
	 
	-- bags
	TukuiConfigUILocalization.bags = "Taschen"
	TukuiConfigUILocalization.bagsenable = "Aktiviere All-In-One Taschen"
	 
	-- datatext
	TukuiConfigUILocalization.datatext = "Infotext"
	TukuiConfigUILocalization.datatexttime24 = "Aktiviere 24-Stunden-Zeitanzeige"
	TukuiConfigUILocalization.datatextlocaltime = "Zeige Ortszeit, anstelle von Serverzeit"
	TukuiConfigUILocalization.datatextbattleground = "Aktiviere Schlachtfeld Anzeige"
	TukuiConfigUILocalization.datatexthps_text = "Heilung pro Sekunde, Position (0 für deaktiviert)"
	TukuiConfigUILocalization.datatextguild = "Gilde Position (0 für deaktiviert)"
	TukuiConfigUILocalization.datatext_arp = "Rüstungsdurchschlag Position (0 für deaktiviert)"
	TukuiConfigUILocalization.datatextsystem = "Speicher Position (0 für deaktiviert)"
	TukuiConfigUILocalization.datatextbags = "Taschen Position (0 für deaktiviert)"
	TukuiConfigUILocalization.datatextfontsize = "Schriftgröße des Text"
	TukuiConfigUILocalization.datatextfps_ms = "Latenz und FPS Position (0 für deaktiviert)"
	TukuiConfigUILocalization.datatextarmor = "Rüstung Position (0 für deaktiviert)"
	TukuiConfigUILocalization.datatextavd = "Vermeidung position (0 für deaktiviert)"
	TukuiConfigUILocalization.datatextpower = "Zaubermacht/Angriffskraft Position (0 für deaktiviert)"
	TukuiConfigUILocalization.datatexthaste = "Tempowertung Position (0 für deaktiviert)"
	TukuiConfigUILocalization.datatextfriends = "Freunde Position (0 für deaktiviert)"
	TukuiConfigUILocalization.datatextwowtime = "Zeit Position (0 für deaktiviert)"
	TukuiConfigUILocalization.datatextgold = "Gold Position (0 für deaktiviert)"
	TukuiConfigUILocalization.datatextdps_text = "Schaden pro Sekunde Position (0 für deaktiviert)"
	TukuiConfigUILocalization.datatextcrit = "Crit % position (0 für deaktiviert)"
	TukuiConfigUILocalization.datatextdur = "Haltbarkeit Position (0 für deaktiviert)"
	TukuiConfigUILocalization.datatextcurrency = "Währung Position (0 für deaktiviert)"
	TukuiConfigUILocalization.datatextmicromenu = "Micro Menu Position (0 für deaktiviert)"
	TukuiConfigUILocalization.datatexthit = "Trefferwertung Position (0 für deaktiviert)"
	TukuiConfigUILocalization.datatextmastery = "Meisterschaft Position (0 für deaktiviert)"
	TukuiConfigUILocalization.datatexttalent = "Zeige Spezalisierung (0 für deaktiviert)"
	TukuiConfigUILocalization.datatextcalltoarms = "Ruf zu den Waffen & Dungeons (0 für deaktiviert)"

	 
	-- unit frames
	TukuiConfigUILocalization.unitframes = "Einheitenfenster"
	TukuiConfigUILocalization.unitframescombatfeedback = "Kampfmeldungen auf Spieler und Ziel"
	TukuiConfigUILocalization.unitframesrunebar = "Aktiviere Runenleiste für Todesritter"
	TukuiConfigUILocalization.unitframesauratimer = "Aktiviere Dauer auf Stärkungs- und Schwächungszaubern"
	TukuiConfigUILocalization.unitframestotembar = "Aktiviere Totemleiste für Schamanen"
	TukuiConfigUILocalization.unitframesshowtotalhpmp = "Zeige gesamtes Leben/Mana an"
	TukuiConfigUILocalization.unitframesshowplayerinparty = "Zeige sich selbst in der Gruppe"
	TukuiConfigUILocalization.unitframesraidunitdebuffwatch = "Aktiviere PvE Überwachung von Stärkungs- und Schwächungszaubern (nur Grid)"
	TukuiConfigUILocalization.unitframesunitcastbar = "Aktiviere Zauberleiste"
	TukuiConfigUILocalization.unitframestargetauras = "Aktiviere Stärkungs- und Schwächungszauber auf dem Ziel"
	TukuiConfigUILocalization.unitframessaveperchar = "Positionen der Einheitenfenster pro Charakter speichern"
	TukuiConfigUILocalization.unitframesplayeraggro = "Aktiviere Bedrohungsanzeige"
	TukuiConfigUILocalization.unitframesshowsmooth = "Aktiviere flüssigere Leistenänderungen"
	TukuiConfigUILocalization.unitframescharportrait = "Aktiviere Portrait für Spieler und Ziel"
	TukuiConfigUILocalization.unitframesenable = "Aktiviere Tukui Einheitenfenster"
	TukuiConfigUILocalization.unitframestargetpowerpvponly = "Zeige Mana/Wut/Energie nur bei Gegnern an"
	TukuiConfigUILocalization.unitframesgridonly = "Aktiviere Grid nur für das Heilerlayout"
	TukuiConfigUILocalization.unitframeshealcomm = "Aktiviere HealCom"
	TukuiConfigUILocalization.unitframesfocusdebuff = "Aktiviere Anzeige von Schwächungszauber auf Fokusziel"
	TukuiConfigUILocalization.unitframesaggro = "Aktiviere Bedrohungsanzeige des Schlachtzugs/Gruppe"
	TukuiConfigUILocalization.unitframesshowboss = "Aktiviere Einheitsfenster von Bossen"
	TukuiConfigUILocalization.unitframesenemyhcolor = "Färbe Lebensbalken der Gegner nach Feindseligkeit (für PVP)"
	TukuiConfigUILocalization.unitframesgridhealthvertical = "Lebensbalken bei Grid vertikal anzeigen"
	TukuiConfigUILocalization.unitframesshowsymbols = "Zeige Symbole bei Gruppe/Schlachtzug"
	TukuiConfigUILocalization.unitframesthreatbar = "Aktiviere Bedrohungsleiste"
	TukuiConfigUILocalization.unitframesshowrange = "Aktiviere Entfernungsanzeige für Schlachtzug/Gruppe"
	TukuiConfigUILocalization.unitframesfocus = "Aktiviere Fokusziel"
	TukuiConfigUILocalization.unitframescblatency = "Zeige Zauberleistenlatenz"
	TukuiConfigUILocalization.unitframescbicons = "Zeige Icons an der Zauberleiste"
	TukuiConfigUILocalization.unitframesplayerauras = "Aktiviere alternativen Stärkungs-/Schwächungszauber-Modus für Spieler"
	TukuiConfigUILocalization.unitframesauratextscale = "Textskalierung auf  Stärkungs-/Schwächungszaubern"
	TukuiConfigUILocalization.unitframesgridscale = "Grid Skalierung"
	TukuiConfigUILocalization.unitframesmanahigh = "Hohes Mana Indikator (für Jäger)"
	TukuiConfigUILocalization.unitframeslowThreshold = "Wenig Mana Indikator (Für alle Mana Klassen)"
	TukuiConfigUILocalization.unitframesraidalphaoor = "Transparenz der Schlachtzug- und Gruppenfenster wenn außer Reichweite"
	TukuiConfigUILocalization.unitframesmaintank = "Main Tank Anzeige aktivieren"
	TukuiConfigUILocalization.unitframesmainassist = "Main Assist Anzeige aktivieren"
	TukuiConfigUILocalization.unitframesunicolor = "Einheitliches Farbschema (graue Lebensbalken) aktivieren"
	TukuiConfigUILocalization.unitframestotdebuffs = "Ziel vom Ziel Schwächungszauber anzeigen (hohe Auflösung)"
	TukuiConfigUILocalization.unitframesclassbar = "Aktiviere Klassenleiste"
	TukuiConfigUILocalization.unitframesweakenedsoulbar = "Aktiviere 'Geschwächte Seele' Anzeige (Priester)"
	TukuiConfigUILocalization.unitframesonlyselfdebuffs = "Zeigt nur deine debuffs auf dem Ziel an"
	TukuiConfigUILocalization.unitframesshowfocustarget = "Aktiviere Fokus Ziel"
	TukuiConfigUILocalization.unitframesbordercolor = "Rahmenfarbe der Panels"
	TukuiConfigUILocalization.unitframesmovecombobar = "Bewege die Kombopunkte vom Ziel (nur Schurke)"
	TukuiConfigUILocalization.unitframesclassiccombo = "Benutze klassische Kombopunktanzeige"
	TukuiConfigUILocalization.unitframesgridvertical = "Gridausrichtung vertikal anstatt horizontal"
	TukuiConfigUILocalization.unitframesraid = "Aktiviere das Tukui Schlachtzugsfenster"
	TukuiConfigUILocalization.unitframesshowraidpets = "Zeige die Begleiter im Tukui Schlachtzugsfenster"
	TukuiConfigUILocalization.unitframesdruidmanabar = "Zeige die Manaleiste in Bär-/Katzenform (Druide)"
	TukuiConfigUILocalization.unitframesdruidmushroombar = "Zeige die Wildpilz-Leiste in der Gleichgewichts- oder Wiederherstellungsspezialisierung (Druide)"
	TukuiConfigUILocalization.unitframesmageclassbar = "Zeige die Leiste für Arkane Ladungen (Magier)"
	TukuiConfigUILocalization.unitframesraidunitspercolumn = "Anzahl der Schlachtzugseinheiten per Spalte/Reihe"
	TukuiConfigUILocalization.unitframesmaxraidplayers = "Max raid frames displayed according to instance max players"
	TukuiConfigUILocalization.unitframesshowstatuebar = "Show Statue Bar (Dependencies: Class Bar Option need to be enabled)"
	TukuiConfigUILocalization.unitframesshowgroupresurrect = "Show ressurect icon on raid frames"
	 
	-- loot
	TukuiConfigUILocalization.loot = "Beute"
	TukuiConfigUILocalization.lootlootframe = "Aktiviere Beutefenster"
	TukuiConfigUILocalization.lootautogreed = "Aktiviere automatisch-Gier Würfeln für grüne Gegenstände (falls max. Level erreicht)"
	TukuiConfigUILocalization.lootrolllootframe = "Aktiviere Würfelfenster"
	 
	-- invite
	TukuiConfigUILocalization.invite = "Einladung"
	TukuiConfigUILocalization.inviteautoaccept = "Einladungen von Freunden & Gildenmitgliedern automatisch annehmen"
	 
	-- tooltip
	TukuiConfigUILocalization.tooltip = "Tooltip"
	TukuiConfigUILocalization.tooltipenable = "Aktiviere Tooltip"
	TukuiConfigUILocalization.tooltiphidecombat = "Verstecke Tooltip in Kampf"
	TukuiConfigUILocalization.tooltiphidebuttons = "Verstecke Tooltip an Aktionsleisten"
	TukuiConfigUILocalization.tooltiphideuf = "Verstecke Tooltip an Einheitenfenstern"
	TukuiConfigUILocalization.tooltipcursor = "Tooltip am Mauszeiger anzeigen"
	 
	-- error
	TukuiConfigUILocalization.error = "Fehlermeldung"
	TukuiConfigUILocalization.errorenable = "Verstecke rote Meldungen in der Mitte des Bildschirms"
	 
	-- action bar
	TukuiConfigUILocalization.actionbar = "Aktionsleisten"
	TukuiConfigUILocalization.actionbarhideshapeshift = "Verstecke Gestaltenwandler- oder Totemleiste"
	TukuiConfigUILocalization.actionbarshowgrid = "Rahmen auf Aktionsleisten immer anzeigen"
	TukuiConfigUILocalization.actionbarenable = "Aktiviere Tukui Aktionsleisten"
	TukuiConfigUILocalization.actionbarrb = "Aktiviere Mouseover für rechte Aktionsleisten"
	TukuiConfigUILocalization.actionbarhotkey = "Zeige Tastenbelegung auf den Buttons"
	TukuiConfigUILocalization.actionbarssmo = "Gestaltenwandler- oder Totemleiste nur bei Mouseover anzeigen"
	TukuiConfigUILocalization.actionbarrbn = "Anzahl der Aktionsleisten unten (1 oder 2)"
	TukuiConfigUILocalization.actionbarrn = "Anzahl der Aktionsleisten rechts (1, 2 oder 3)"
	TukuiConfigUILocalization.actionbarbuttonsize = "Größe der Aktionsleisten Buttons"
	TukuiConfigUILocalization.actionbarbuttonspacing = "Abstand der Aktionsleisten Buttons"
	TukuiConfigUILocalization.actionbarpetbuttonsize = "Größe der Begleiter/Gestaltenwandler Buttons"
	TukuiConfigUILocalization.actionbarownshdbar = "Benutze eine leere Leiste für Schattentanz (Schurke) anstatt der Verstohlenheitsleiste"
	TukuiConfigUILocalization.actionbarownmetabar = "Benutze eine leere Leiste für Metamorphose (Hexenmeister) anstatt der Hauptleiste"
	TukuiConfigUILocalization.actionbarownwarstancebar = "Nutze eine leere Leiste für jede Haltung (Krieger) anstelle der Haupt-Leiste"
	TukuiConfigUILocalization.actionbarmacro = "Zeige Makro-Text auf der Aktionsleiste"
	 
	-- arena
	TukuiConfigUILocalization.arena = "Arena"
	TukuiConfigUILocalization.unitframesarena = "Aktiviere Arenaeinheitenfenster"
	 
	-- cooldowns
	TukuiConfigUILocalization.cooldown = "Abklingzeiten"
	TukuiConfigUILocalization.cooldownenable = "Aktiviere Anzeige der Abklingzeit auf Buttons"
	TukuiConfigUILocalization.cooldowntreshold = "Färbe Anzeige der Abklingzeiten ab Wert X rot"
	 
	-- chat
	TukuiConfigUILocalization.chat = "Geselligkeit"
	TukuiConfigUILocalization.chatenable = "Aktiviere Tukui Chat"
	TukuiConfigUILocalization.chatwhispersound = "Beim Empfang von Flüsternachrichten Ton abspielen"
	TukuiConfigUILocalization.chatbackground = "Aktiviere die Hintergrundpanel der Chatfenster"

	-- buff
	TukuiConfigUILocalization.auras = "Auren"
	TukuiConfigUILocalization.aurasplayer = "Aktiviere Tukui Stärkungs/Schwächungszauberanzeige"
	TukuiConfigUILocalization.aurasconsolidate = "Aktiviere zusammengelegte Stärkungszauber"
	TukuiConfigUILocalization.aurasflash = "Aktiviere blinkende Animation für Auren mit weniger als 30 Sekunden"
	TukuiConfigUILocalization.aurasclassictimer = "Zeige den klassischen Timer für Spielerauren"
	TukuiConfigUILocalization.aurashidedebuffs = "Hide Debuffs"

	-- buttons
	TukuiConfigUILocalization.option_button_reset = "Zurücksetzen"
	TukuiConfigUILocalization.option_button_load = "Anwenden"
	TukuiConfigUILocalization.option_button_close = "Schließen"
	TukuiConfigUILocalization.option_setsavedsetttings = "Einstellungen pro Charakter speichern"
	TukuiConfigUILocalization.option_resetchar = "Bist du sicher, dass du die Einstellungen für diesen Charakter auf Standard zurücksetzen willst?"
	TukuiConfigUILocalization.option_resetall = "Bist du sicher, dass du alle Einstellungen auf Standard zurücksetzen willst?"
	TukuiConfigUILocalization.option_perchar = "Bist du sicher, dass du die Einstellung für 'Einstellungen pro Charakter' wechseln willst?"
	TukuiConfigUILocalization.option_makeselection = "Du musst erst eine Auswahl treffen bevor Du mit den Einstellungen fortfahren können."
end