-- localization for Italian made by Oz (http://www.tukui.org/forums/profile.php?id=5749)
if GetLocale() == "itIT" then
	-- general
	TukuiConfigUILocalization.general = "Generale"
	TukuiConfigUILocalization.generalautoscale = "Scala automatica della UI."
	TukuiConfigUILocalization.generaloverridelowtohigh = "Utilizza la disposizione per l'alta risoluzione anche a bassa risoluzione."
	TukuiConfigUILocalization.generalmultisampleprotect = "Protezione dal multisampling (bordi perfetti di 1 pixel)."
	TukuiConfigUILocalization.generaluiscale = "Scala della UI (se la scala automatica è disabilitata)."
	TukuiConfigUILocalization.generalbackdropcolor = "Imposta il colore di sfondo dei pannelli."
	TukuiConfigUILocalization.generalbordercolor = "Imposta il colore dei bordi dei pannelli."
	TukuiConfigUILocalization.generalblizzardreskin = "Ridisegna i riquadri Blizzard per intonarsi a Tukui."
	TukuiConfigUILocalization.generalmultiplescreendamage = "Attiva il testo dei danni per schermi multipli (surround/eyefinity)."
	 
	-- nameplate
	TukuiConfigUILocalization.nameplate = "Barre delle unità"
	TukuiConfigUILocalization.nameplateenable = "Attiva le barre delle unità Tukui."
	TukuiConfigUILocalization.nameplateenhancethreat = "Attiva la funzionalità di rilevamento della minaccia, che si adatterà in automatico al tuo ruolo."
	TukuiConfigUILocalization.nameplateshowhealth = "Mostra la salute sulla barra delle unità."
	TukuiConfigUILocalization.nameplatecombat = "Mostra soltanto le barre delle unità nemiche in combattimento."
	TukuiConfigUILocalization.nameplategoodcolor = "Colore per un livello positivo di minaccia, a seconda se sei difensore o assaltatore/guaritore."
	TukuiConfigUILocalization.nameplatebadcolor = "Colore per un livello negativo di minaccia, a seconda se sei difensore o assaltatore/guaritore."
	TukuiConfigUILocalization.nameplatetransitioncolor = "Colore di guadagno/perdita minaccia."
	 
	-- merchant
	TukuiConfigUILocalization.merchant = "Mercante"
	TukuiConfigUILocalization.merchantsellgrays = "Vendi automaticamente le cianfrusaglie."
	TukuiConfigUILocalization.merchantautorepair = "Ripara automaticamente gli oggetti."
	TukuiConfigUILocalization.merchantsellmisc = "Vendi automaticamente alcuni oggetti predefiniti (oggetti inutili, cianfrusaglie escluse)."
	 
	-- bags
	TukuiConfigUILocalization.bags = "Sacche"
	TukuiConfigUILocalization.bagsenable = "Attiva la sacca unica."
	 
	-- datatext
	TukuiConfigUILocalization.datatext = "Testi informativi"
	TukuiConfigUILocalization.datatexttime24 = "Mostra l'orario a 24 ore."
	TukuiConfigUILocalization.datatextlocaltime = "Utilizza l'orario locale piuttosto che l'orario del reame."
	TukuiConfigUILocalization.datatextbattleground = "Mostra le statistiche dei campi di battaglia."
	TukuiConfigUILocalization.datatexthps_text = "Cure al secondo, posizione (0 per disattivarlo)."
	TukuiConfigUILocalization.datatextguild = "Gilda, posizione (0 per disattivarlo)."
	TukuiConfigUILocalization.datatext_arp = "Penetrazione dell'armatura, posizione (0 per disattivarlo)."
	TukuiConfigUILocalization.datatextsystem = "Memoria, posizione (0 per disattivarlo)."
	TukuiConfigUILocalization.datatextbags = "Sacche, posizione (0 per disattivarlo)."
	TukuiConfigUILocalization.datatextfontsize = "Dimensione del carattere del testo."
	TukuiConfigUILocalization.datatextfps_ms = "FPS e latenza, posizione (0 per disattivarlo)."
	TukuiConfigUILocalization.datatextarmor = "Armatura, posizione (0 per disattivarlo)."
	TukuiConfigUILocalization.datatextavd = "Elusione, posizione (0 per disattivarlo)."
	TukuiConfigUILocalization.datatextpower = "Potere, posizione (0 per disattivarlo)."
	TukuiConfigUILocalization.datatexthaste = "Celerità, posizione (0 per disattivarlo)."
	TukuiConfigUILocalization.datatextfriends = "Amici, posizione (0 per disattivarlo)."
	TukuiConfigUILocalization.datatextwowtime = "Orario, posizione (0 per disattivarlo)."
	TukuiConfigUILocalization.datatextgold = "Denaro, posizione (0 per disattivarlo)."
	TukuiConfigUILocalization.datatextdps_text = "Danni al secondo, posizione (0 per disattivarlo)."
	TukuiConfigUILocalization.datatextcrit = "% di critico, posizione (0 per disattivarlo)."
	TukuiConfigUILocalization.datatextdur = "Condizioni dell'armatura, posizione (0 per disattivarlo)."
	TukuiConfigUILocalization.datatextcurrency = "Valuta, posizione (0 per disattivarlo)."
	TukuiConfigUILocalization.datatextmicromenu = "Micro menu, posizione (0 per disattivarlo)."
	TukuiConfigUILocalization.datatexthit = "Impatto, posizione (0 per disattivarlo)."
	TukuiConfigUILocalization.datatextmastery = "Maestria, posizione (0 per disattivarlo)."
	TukuiConfigUILocalization.datatexttalent = "Visualizzatore dei talenti, posizione (0 per disattivarlo)."
	TukuiConfigUILocalization.datatextcalltoarms = "Chiamata alle armi e dungeons, posizione (0 per disattivarlo)."
	TukuiConfigUILocalization.datatextregen = MANA_REGEN_ABBR

	 
	-- unit frames
	TukuiConfigUILocalization.unitframes = "Riquadri delle unità"
	TukuiConfigUILocalization.unitframescombatfeedback = "Mostra il testo di combattimento su giocatore e bersaglio."
	TukuiConfigUILocalization.unitframesrunebar = "Mostra la barra delle rune del cavaliere della morte."
	TukuiConfigUILocalization.unitframesauratimer = "Mostra il timer sulle auree."
	TukuiConfigUILocalization.unitframestotembar = "Mostra la barra dei totems dello sciamano."
	TukuiConfigUILocalization.unitframesshowtotalhpmp = "Visualizza il totale di salute/potere."
	TukuiConfigUILocalization.unitframesshowplayerinparty = "Mostra te stesso in gruppo."
	TukuiConfigUILocalization.unitframesraidunitdebuffwatch = "Attiva il monitoraggio delle auree nelle incursioni PvA (solo con la disposizione a griglia)."
	TukuiConfigUILocalization.unitframesunitcastbar = "Mostra la barra incantesimi."
	TukuiConfigUILocalization.unitframestargetauras = "Mostra le auree del bersaglio."
	TukuiConfigUILocalization.unitframessaveperchar = "Salva la posizione dei riquadri delle unità per-personaggio."
	TukuiConfigUILocalization.unitframesplayeraggro = "Attiva il visualizzatore dell'aggressione su di te."
	TukuiConfigUILocalization.unitframesshowsmooth = "Attiva la barra a cambiamento graduale."
	TukuiConfigUILocalization.unitframescharportrait = "Attiva i ritratti su giocatore e bersaglio."
	TukuiConfigUILocalization.unitframesenable = "Attiva i riquadri delle unità Tukui."
	TukuiConfigUILocalization.unitframestargetpowerpvponly = "Visualizza il potere solo sui nemici."
	TukuiConfigUILocalization.unitframesgridonly = "Attiva soltanto il modello a griglia per la disposione da guaritore."
	TukuiConfigUILocalization.unitframeshealcomm = "Attiva la visualizzazione delle cure in arrivo."
	TukuiConfigUILocalization.unitframesfocusdebuff = "Mostra le penalità del focus."
	TukuiConfigUILocalization.unitframesaggro = "Attiva il visualizzatore dell'aggressione su gruppo/incursione."
	TukuiConfigUILocalization.unitframesshowboss = "Mostra i riquadri delle unità dei bosses."
	TukuiConfigUILocalization.unitframesenemyhcolor = "Colora la saluta nemica a seconda dell'ostilità (per il PvP)."
	TukuiConfigUILocalization.unitframesgridhealthvertical = "Mostra verticalmente la barra della salute per la disposizione a griglia."
	TukuiConfigUILocalization.unitframesshowsymbols = "Mostra i simboli su gruppo/incursione."
	TukuiConfigUILocalization.unitframesthreatbar = "Attiva la barra della minaccia."
	TukuiConfigUILocalization.unitframesshowrange = "Attiva il cambio di trasparenza in base alla distanza per gruppo/incursione."
	TukuiConfigUILocalization.unitframesfocus = "Mostra il bersaglio del focus."
	TukuiConfigUILocalization.unitframescblatency = "Mostra la latenza della barra incantesimi."
	TukuiConfigUILocalization.unitframescbicons = "Mostra le icone della barra incantesimi."
	TukuiConfigUILocalization.unitframesplayerauras = "Attiva per il giocatore una modalità alternativa di gestione delle auree."
	TukuiConfigUILocalization.unitframesauratextscale = "Scala del testo di un'aurea sulle icone delle auree."
	TukuiConfigUILocalization.unitframesgridscale = "Scala della griglia."
	TukuiConfigUILocalization.unitframesmanahigh = "Indicatore di mana alto (per i cacciatori)."
	TukuiConfigUILocalization.unitframeslowThreshold = "Indicatore di mana basso (per tutte le classi con mana)"
	TukuiConfigUILocalization.unitframesraidalphaoor = "Grado di trasparenza dell'unità fuori portata in gruppo/incursione"
	TukuiConfigUILocalization.unitframesmaintank = "Mostra il difensore principale."
	TukuiConfigUILocalization.unitframesmainassist = "Mostra l'assistente principale."
	TukuiConfigUILocalization.unitframesunicolor = "Attiva il tema a colore unico (barre della salute grigie)."
	TukuiConfigUILocalization.unitframestotdebuffs = "Mostra le penalità del bersaglio del bersaglio (richiede alta risoluzione)."
	TukuiConfigUILocalization.unitframesclassbar = "Mostra la barra di classe."
	TukuiConfigUILocalization.unitframesweakenedsoulbar = "Attiva la barra di notifica per la penalità anima indebolita (solo per sacerdoti)."
	TukuiConfigUILocalization.unitframesonlyselfdebuffs = "Visualizza soltanto le tue penalità sul bersaglio."
	TukuiConfigUILocalization.unitframesshowfocustarget = "Mostra il bersaglio del focus."
	TukuiConfigUILocalization.unitframesbordercolor = "Imposta il colore del bordo dei pannelli."
	TukuiConfigUILocalization.unitframesraid = "Attiva i riquadri d'incursione Tukui."
	TukuiConfigUILocalization.unitframesshowraidpets = "Mostra i famigli nei riquadri d'incursione Tukui."
	TukuiConfigUILocalization.unitframesdruidmanabar = "Mostra la barra del mana per i druidi in forma d'orso/felina."
	TukuiConfigUILocalization.unitframesdruidmushroombar = "Mostra la barra del fungo selvaggio del druido quando specializzato in equilibrio o ristorazione."
	TukuiConfigUILocalization.unitframesmageclassbar = "Mostra la barra arcana del mago."
	TukuiConfigUILocalization.unitframesraidunitspercolumn = "Numero delle unità d'incursione per colonna/riga."
	TukuiConfigUILocalization.unitframesmaxraidplayers = "Mostra i riquadri d'incursione in accordo al numero massimo di giocatori per l'instance."
	TukuiConfigUILocalization.unitframesshowstatuebar = "Mostra la barra delle statue (dipendenza: è necessario che la barra di classe sia attiva)."
	TukuiConfigUILocalization.unitframesmovecombobar = "Sgancia dal bersaglio la barra dei punti combo (solo per i ladri)."
	TukuiConfigUILocalization.unitframesclassiccombo = "Usa i punti combo classici."
	TukuiConfigUILocalization.unitframesgridvertical = "Visualizza verticalmente i gruppi d'incursione sulla griglia."
	TukuiConfigUILocalization.unitframesshowgroupresurrect = "Mostra l'icona della resurrezione sui riquadri d'incursione."

	-- loot
	TukuiConfigUILocalization.loot = "Bottino"
	TukuiConfigUILocalization.lootlootframe = "Attiva la finestra del bottino Tukui."
	TukuiConfigUILocalization.lootautogreed = "Al massimo livello, attiva la bramosia automatica per gli oggetti verdi."
	TukuiConfigUILocalization.lootrolllootframe = "Mostra la finestra dei tiri per il bottino."
	 
	-- invite
	TukuiConfigUILocalization.invite = "Inviti"
	TukuiConfigUILocalization.inviteautoaccept = "Attiva l'invito automatico (per amici e compagni di gilda)."
	 
	-- tooltip
	TukuiConfigUILocalization.tooltip = "Suggerimenti"
	TukuiConfigUILocalization.tooltipenable = "Mostra i suggerimenti."
	TukuiConfigUILocalization.tooltiphidecombat = "Nascondi i suggerimenti in combattimento."
	TukuiConfigUILocalization.tooltiphidebuttons = "Nascondi i suggerimenti sugli scomparti delle barre delle azioni."
	TukuiConfigUILocalization.tooltiphideuf = "Nascondi i suggerimenti sui riquadri delle unità."
	TukuiConfigUILocalization.tooltipcursor = "Àncora i suggerimenti al cursore del mouse."
	 
	-- error
	TukuiConfigUILocalization.error = "Messaggi d'errore"
	TukuiConfigUILocalization.errorenable = "Nascondi lo spam dei messaggi d'errore al centro dello schermo."
	 
	-- action bar
	TukuiConfigUILocalization.actionbar = "Barre delle azioni"
	TukuiConfigUILocalization.actionbarhideshapeshift = "Nascondi la 'barra mutaforma'."
	TukuiConfigUILocalization.actionbarshowgrid = "Mostra la griglia degli scomparti delle barre dell'azioni."
	TukuiConfigUILocalization.actionbarenable = "Attiva le barre delle azioni Tukui."
	TukuiConfigUILocalization.actionbarrb = "Mostra la barra a destra al passaggio del cursore del mouse."
	TukuiConfigUILocalization.actionbarhotkey = "Mostra i tasti di assegnazione rapida sugli scomparti."
	TukuiConfigUILocalization.actionbarssmo = "Mostra la 'barra mutaforma' al passaggio del cursore del mouse."
	TukuiConfigUILocalization.actionbarrbn = "Numero delle barre delle azioni in basso (1 o 2)."
	TukuiConfigUILocalization.actionbarrn = "Numero delle barre delle azioni sulla destra (0, 1, 2 o 3)."
	TukuiConfigUILocalization.actionbarbuttonsize = "Dimensioni degli scomparti della barra delle azioni principale."
	TukuiConfigUILocalization.actionbarbuttonspacing = "Spazio tra gli scomparti della barra delle azioni principale."
	TukuiConfigUILocalization.actionbarpetbuttonsize = "Dimensione degli scomparti della barra del famiglio e della 'barra mutaforma'."
	TukuiConfigUILocalization.actionbarownshdbar = "Utilizza un barra vuota per la danza dell'ombra (ladro) piuttosto che la 'barra furtività'."
	TukuiConfigUILocalization.actionbarownmetabar = "Utilizza una barra vuota per la metamorfosi (stregone) piuttosto che la barra principale."
	TukuiConfigUILocalization.actionbarownwarstancebar = "Utilizza una barra vuota per ciascuna postura (guerriero) piuttosto che la barra principale."
	TukuiConfigUILocalization.actionbarmacro = "Mostra il testo di una macro sulle barre delle azioni."
	 
	-- arena
	TukuiConfigUILocalization.arena = "Arena"
	TukuiConfigUILocalization.unitframesarena = "Mostra i riquadri delle unità per l'arena."
	 
	-- cooldowns
	TukuiConfigUILocalization.cooldown = "Recuperi"
	TukuiConfigUILocalization.cooldownenable = "Mostra il numero del recupero sui pulsanti."
	TukuiConfigUILocalization.cooldowntreshold = "Rendi rosso il numero del recupero a un dato valore X."
	 
	-- chat
	TukuiConfigUILocalization.chat = "Chat"
	TukuiConfigUILocalization.chatenable = "Attiva la chat Tukui."
	TukuiConfigUILocalization.chatwhispersound = "Ricevi un suono quando t'arriva un messaggio privato."
	TukuiConfigUILocalization.chatbackground = "Mostra il pannello di sfondo della chat."

	-- buff
	TukuiConfigUILocalization.auras = "Auree"
	TukuiConfigUILocalization.aurasplayer = "Attiva i riquadri Tukui per benefici/penalità."
	TukuiConfigUILocalization.aurasconsolidate = "Mostra i benefici consolidati."
	TukuiConfigUILocalization.aurasflash = "Attiva un'animazione intermittente sulle auree con meno di 30 secondi di durata."
	TukuiConfigUILocalization.aurasclassictimer = "Visualizza il timer classico sui benefici del giocatore."
	TukuiConfigUILocalization.aurashidedebuffs = "Nascondi le penalità."

	-- buttons
	TukuiConfigUILocalization.option_button_reset = "Reinizializza"
	TukuiConfigUILocalization.option_button_load = "Applica impostazioni"
	TukuiConfigUILocalization.option_button_close = "Chiudi"
	TukuiConfigUILocalization.option_setsavedsetttings = "Configura le impostazioni per-personaggio"
	TukuiConfigUILocalization.option_resetchar = "Vuoi davvero reinizializzare le impostazioni del tuo personaggio in modo che corrispondano alle impostazioni di partenza?"
	TukuiConfigUILocalization.option_resetall = "Vuoi davvero riportare tutte le tue impostazioni a quelle di partenza?"
	TukuiConfigUILocalization.option_perchar = "Vuoi davvero attivare (o disattivare) le impostazioni per-personaggio?"
	TukuiConfigUILocalization.option_makeselection = "Devi fare una scelta prima di poter continuare!"
end