-- localization for italian made by Iceky (http://www.tukui.org/forums/profile.php?id=42201)
if GetLocale() == "itIT" then
	-- general
	TukuiConfigUILocalization.general = "Generale"
	TukuiConfigUILocalization.generalautoscale = "Auto UI Scale"
	TukuiConfigUILocalization.generaloverridelowtohigh = "Utilizza layout risoluzione alta su risoluzione bassa"
	TukuiConfigUILocalization.generalmultisampleprotect = "Protezione Multisampling (Pulisce 1px border)"
	TukuiConfigUILocalization.generaluiscale = "UI Scale (se auto-scale è disabilitato)"
	TukuiConfigUILocalization.generalbackdropcolor = "Imposta il colore dello sfondo di default per i pannelli"
	TukuiConfigUILocalization.generalbordercolor = "Imposta il colore del bordo per i pannelli"
	TukuiConfigUILocalization.generalblizzardreskin = "Reskin Blizzard frames in modo che corrisponda a Tukui"
	TukuiConfigUILocalization.generalbigwigsreskin = "Reskin Big Wigs frames in modo che corrisponda a Tukui"
	 
	-- nameplate
	TukuiConfigUILocalization.nameplate = "Nameplates"
	TukuiConfigUILocalization.nameplateenable = "Abilita Nameplates"
	TukuiConfigUILocalization.nameplateenhancethreat = "Abilita la caratteristica minaggia, cambia automaticamente in base al ruolo"
	TukuiConfigUILocalization.nameplateshowhealth = "Mostra vita sul nameplate"
	TukuiConfigUILocalization.nameplatecombat = "Visualizza il nameplate nemico solo in combattimento"
	TukuiConfigUILocalization.nameplategoodcolor = "Colore buona minaccia, varia in base se si è tank o dps/heal"
	TukuiConfigUILocalization.nameplatebadcolor = "Colore cattiva minaccia, varia in base se si è tank o dps/heal"
	TukuiConfigUILocalization.nameplatetransitioncolor = "Colore perdi/acquisisci minaccia"
	 
	-- merchant
	TukuiConfigUILocalization.merchant = "Mercante"
	TukuiConfigUILocalization.merchantsellgrays = "Vendita automatica item grigi"
	TukuiConfigUILocalization.merchantautorepair = "Riparazione automatica item"
	TukuiConfigUILocalization.merchantsellmisc = "Vendi alcuni item definiti in modo automatico (non grigi)"
	 
	-- bags
	TukuiConfigUILocalization.bags = "Zaini"
	TukuiConfigUILocalization.bagsenable = "Abilita zaino unico"
	 
	-- datatext
	TukuiConfigUILocalization.datatext = "Data Text"
	TukuiConfigUILocalization.datatexttime24 = "Abilita ora 24h"
	TukuiConfigUILocalization.datatextlocaltime = "Utilizza ora locale invece che l'ora del server"
	TukuiConfigUILocalization.datatextbattleground = "Abilita statistiche campo di battaglia"
	TukuiConfigUILocalization.datatexthps_text = "Cure al secondo, posizione (0 per disabilitato)"
	TukuiConfigUILocalization.datatextguild = "Gilda posizione (0 per disabilitato)"
	TukuiConfigUILocalization.datatext_arp = "Penetrazione Armatura posizione (0 per disabilitato)"
	TukuiConfigUILocalization.datatextsystem = "Memoria posizione (0 per disabilitato)"
	TukuiConfigUILocalization.datatextbags = "Zaini posizione (0 per disabilitato)"
	TukuiConfigUILocalization.datatextfontsize = "Dimensioni font per il testo"
	TukuiConfigUILocalization.datatextfps_ms = "Latency e FPS posizione (0 per disabilitato)"
	TukuiConfigUILocalization.datatextarmor = "Armatura posizione (0 per disabilitato)"
	TukuiConfigUILocalization.datatextavd = "Schivare posizione (0 per disabilitato)"
	TukuiConfigUILocalization.datatextpower = "Potenza posizione (0 per disabilitato)"
	TukuiConfigUILocalization.datatexthaste = "Celerità posizione (0 per disabilitato)"
	TukuiConfigUILocalization.datatextfriends = "Amici posizione (0 per disabilitato)"
	TukuiConfigUILocalization.datatextwowtime = "Ora posizione (0 per disabilitato)"
	TukuiConfigUILocalization.datatextgold = "Gold posizione (0 per disabilitato)"
	TukuiConfigUILocalization.datatextdps_text = "Danno al secondo posizione (0 per disabilitato)"
	TukuiConfigUILocalization.datatextcrit = "Crit % posizione (0 per disabilitato)"
	TukuiConfigUILocalization.datatextdur = "Durabilità posizione (0 per disabilitato)"
	TukuiConfigUILocalization.datatextcurrency = "Valuta posizione (0 per disabilitato)"
	TukuiConfigUILocalization.datatextmicromenu = "Micro Menu posizione (0 per disabilitato)"
	TukuiConfigUILocalization.datatexthit = "Impatto posizione (0 per disabilitato)"
	TukuiConfigUILocalization.datatextmastery = "Maestria posizione (0 per disabilitato)"
	TukuiConfigUILocalization.datatexttalent = "Mostra talenti (0 per disabilitato)"
	TukuiConfigUILocalization.datatextcalltoarms = "Call to Arms & Dungeons (0 per disabilitato)"
	TukuiConfigUILocalization.datatextregen = MANA_REGEN_ABBR
	TukuiConfigUILocalization.unitframesmovecombobar = "Muovi la barra combo dal target (SOLO ROGUE)"
	TukuiConfigUILocalization.unitframesclassiccombo = "Usa la classica combo point"
	TukuiConfigUILocalization.unitframesgridvertical = "Visualizza il raid on Grid verticalmente"

	 
	-- unit frames
	TukuiConfigUILocalization.unitframes = "Unit Frames"
	TukuiConfigUILocalization.unitframescombatfeedback = "Feedback in combattiemnto su player e target"
	TukuiConfigUILocalization.unitframesrunebar = "Abilita barra delle rune per cavaliere della morte"
	TukuiConfigUILocalization.unitframesauratimer = "Abilita tempo su aura"
	TukuiConfigUILocalization.unitframestotembar = "Abilita barra dei totem per sciamano"
	TukuiConfigUILocalization.unitframesshowtotalhpmp = "Visualizza il totale di vita/potenza"
	TukuiConfigUILocalization.unitframesshowplayerinparty = "Visualizza te stesso nel party"
	TukuiConfigUILocalization.unitframesraidunitdebuffwatch = "Abilita PVE raid Aura Watch (Solo Grid)"
	TukuiConfigUILocalization.unitframesunitcastbar = "Abilita la barra del cast"
	TukuiConfigUILocalization.unitframestargetauras = "Abilita l'aura del target"
	TukuiConfigUILocalization.unitframessaveperchar = "Salva la posizione dell'unit frame per personaggio"
	TukuiConfigUILocalization.unitframesplayeraggro = "Abilita aggro display su te stesso"
	TukuiConfigUILocalization.unitframesshowsmooth = "Abilita smooth bar"
	TukuiConfigUILocalization.unitframescharportrait = "Abilita ritratto su player e target"
	TukuiConfigUILocalization.unitframesenable = "Abilita Tukui Unit Frames"
	TukuiConfigUILocalization.unitframestargetpowerpvponly = "Abilita Power display solamente sui nemici"
	TukuiConfigUILocalization.unitframesgridonly = "Abilita solo Grid per Healer layout"
	TukuiConfigUILocalization.unitframeshealcomm = "Abilita healcomm"
	TukuiConfigUILocalization.unitframesfocusdebuff = "Abilita Focus debuffs"
	TukuiConfigUILocalization.unitframesaggro = "Abilita aggro display su party/raid"
	TukuiConfigUILocalization.unitframesshowboss = "Abilita Boss Unit Frames"
	TukuiConfigUILocalization.unitframesenemyhcolor = "Colore della vita del nemico (PVP)"
	TukuiConfigUILocalization.unitframesgridhealthvertical = "Visualizza la barra della vita verticalmente per Grid"
	TukuiConfigUILocalization.unitframesshowsymbols = "Visualizza simboli su party/raid"
	TukuiConfigUILocalization.unitframesthreatbar = "Abilita barra della minaccia"
	TukuiConfigUILocalization.unitframesshowrange = "Abilita party/raid Range alpha display"
	TukuiConfigUILocalization.unitframesfocus = "Abilita Focus target"
	TukuiConfigUILocalization.unitframescblatency = "Visualizza latenza sulla barra di cast"
	TukuiConfigUILocalization.unitframescbicons = "Visualizza icone sulla barra di cast"
	TukuiConfigUILocalization.unitframesplayerauras = "Abilita un aura alternatica per il player"
	TukuiConfigUILocalization.unitframesauratextscale = "Aura text scala con l'aura"
	TukuiConfigUILocalization.unitframesgridscale = "Scala Grid"
	TukuiConfigUILocalization.unitframesmanahigh = "Indicatore di mana alto (Per Cacciatore)"
	TukuiConfigUILocalization.unitframeslowThreshold = "Indicatore di mana basso (Tutte le classi con mana)"
	TukuiConfigUILocalization.unitframesraidalphaoor = "Alpha su Party/Raid unit che non sono in range"
	TukuiConfigUILocalization.unitframesmaintank = "Abilita Main Tank"
	TukuiConfigUILocalization.unitframesmainassist = "Abilita Main Assist"
	TukuiConfigUILocalization.unitframesunicolor = "Abilita unico colore per il tema (Barra dela vita grigia)"
	TukuiConfigUILocalization.unitframestotdebuffs = "Abilita Target of Target debuffs (Alta Risoluzione)"
	TukuiConfigUILocalization.unitframesclassbar = "Abilita barra di classe"
	TukuiConfigUILocalization.unitframesweakenedsoulbar = "Abilita barra delle notifiche per Weakened Soul (Prete)"
	TukuiConfigUILocalization.unitframesonlyselfdebuffs = "Visualizza solo i propi debuff sul target"
	TukuiConfigUILocalization.unitframesshowfocustarget = "Abilita Focus target"
	TukuiConfigUILocalization.unitframesbordercolor = "Imposta colore di default per i pannelli"
	TukuiConfigUILocalization.unitframesraid = "Abilita Tukui Raid Frames"
	TukuiConfigUILocalization.unitframesshowraidpets = "Visualizza Pet in Tukui Raid Frames"
	TukuiConfigUILocalization.unitframesdruidmanabar = "Visualizza la barra del mana per il druido in forma Bear/Cat"
	TukuiConfigUILocalization.unitframesdruidmushroombar = "Visualiiza la barra dei funghi del druido in spec Balance o Restoration"
	TukuiConfigUILocalization.unitframesmageclassbar = "Visualizza la barra per il mago arcano"
	TukuiConfigUILocalization.unitframesraidunitspercolumn = "Numero di unità in raid per colonna/riga"
	TukuiConfigUILocalization.unitframesmaxraidplayers = "Max frame del raid in base al massimo dei players"
	TukuiConfigUILocalization.unitframesshowstatuebar = "Show Statue Bar (Dependencies: Class Bar Option need to be enabled)"
	 
	-- loot
	TukuiConfigUILocalization.loot = "Loot"
	TukuiConfigUILocalization.lootlootframe = "Abilita finestra del loot"
	TukuiConfigUILocalization.lootautogreed = "Abilita auto-greed per item versi al massimo livello"
	TukuiConfigUILocalization.lootrolllootframe = "Abilita finestra per il roll dell'item"
	 
	-- invite
	TukuiConfigUILocalization.invite = "Iniviti"
	TukuiConfigUILocalization.inviteautoaccept = "Abilita Auto-Invito (Amici e Gildani)"
	 
	-- tooltip
	TukuiConfigUILocalization.tooltip = "Tooltip"
	TukuiConfigUILocalization.tooltipenable = "Abilita tooltip"
	TukuiConfigUILocalization.tooltiphidecombat = "Nascondi tooltip in combattimento"
	TukuiConfigUILocalization.tooltiphidebuttons = "Nascondi tooltip sui bottoni delle barre di azione"
	TukuiConfigUILocalization.tooltiphideuf = "Nascondi tooltip su unit frames"
	TukuiConfigUILocalization.tooltipcursor = "Abilita tooltip su cursore"
	 
	-- error
	TukuiConfigUILocalization.error = "Messaggi di errore"
	TukuiConfigUILocalization.errorenable = "Nascondi gli errori al centro dello schermo"
	 
	-- action bar
	TukuiConfigUILocalization.actionbar = "Barra delle azioni"
	TukuiConfigUILocalization.actionbarhideshapeshift = "Nascondi la barra Shapeshift o la barra dei totem"
	TukuiConfigUILocalization.actionbarshowgrid = "Visualizza sempre Grid nella barra delle azioni"
	TukuiConfigUILocalization.actionbarenable = "Abilita la barra delle azioni di Tukui"
	TukuiConfigUILocalization.actionbarrb = "Abilita la barra destra su passaggio mouse"
	TukuiConfigUILocalization.actionbarhotkey = "Visualiiza hotkey sui bottoni"
	TukuiConfigUILocalization.actionbarssmo = "Barra Shapeshift bar o barra dei totem su passaggio mouse"
	TukuiConfigUILocalization.actionbarrbn = "Numero di barra delle azioni in basso (1 o 2)"
	TukuiConfigUILocalization.actionbarrn = "Numero di barra delle azioni a destra (0, 1, 2 o 3)"
	TukuiConfigUILocalization.actionbarbuttonsize = "Dimensioni dei principali bottoni"
	TukuiConfigUILocalization.actionbarbuttonspacing = "Spazio dei principali bottoni"
	TukuiConfigUILocalization.actionbarpetbuttonsize = "Dimensioni dei bottoni per pet/shapeshift"
	TukuiConfigUILocalization.actionbarownshdbar = "Utilizza una barra vuota per shadow dance (rogue) invece della barra di stealth"
	TukuiConfigUILocalization.actionbarownmetabar = "Utilizza una barra vuota per Metamorphosis (warlock) invece della barra principale"
	TukuiConfigUILocalization.actionbarownwarstancebar = "Utilizza una barra vuota per ogni stance (warrior) invece della barra principale"
	TukuiConfigUILocalization.actionbarmacro = "Visualizza il testo della macro nell barra delle azioni"
	 
	-- arena
	TukuiConfigUILocalization.arena = "Arena"
	TukuiConfigUILocalization.unitframesarena = "Abilita arena unit frames"
	 
	-- cooldowns
	TukuiConfigUILocalization.cooldown = "Cooldowns"
	TukuiConfigUILocalization.cooldownenable = "Abilita numero cooldown sul bottone"
	TukuiConfigUILocalization.cooldowntreshold = "Cambia il numero del cooldown in rosso al valore X"
	 
	-- chat
	TukuiConfigUILocalization.chat = "Chat"
	TukuiConfigUILocalization.chatenable = "Abilita Tukui Chat"
	TukuiConfigUILocalization.chatwhispersound = "Esegui suono quando ricevi un messaggio privato"
	TukuiConfigUILocalization.chatbackground = "Abilita lo sfondo della chat"

	-- buff
	TukuiConfigUILocalization.auras = "Aura"
	TukuiConfigUILocalization.aurasplayer = "Abilita Tukui Buff/Debuff Frames"
	TukuiConfigUILocalization.aurasconsolidate = "Abilita Buff consolidati"
	TukuiConfigUILocalization.aurasflash = "Abilita flashing automatico sulle auree che hanno meno di 30 secondi"
	TukuiConfigUILocalization.aurasclassictimer = "Visualizza i timer classici sull'aura del player"


	-- buttons
	TukuiConfigUILocalization.option_button_reset = "Reset"
	TukuiConfigUILocalization.option_button_load = "Applica Impostazioni"
	TukuiConfigUILocalization.option_button_close = "Chiudi"
	TukuiConfigUILocalization.option_setsavedsetttings = "Salva impostazioni Per-Personaggio"
	TukuiConfigUILocalization.option_resetchar = "Sei sicuro di voler resettare le impostazioni del personaggio in modo che corrispondano alle tue impostazioni di default?"
	TukuiConfigUILocalization.option_resetall = "Sei sicuro di voler resettare le impostazioni a quelle di default?"
	TukuiConfigUILocalization.option_perchar = "Sei sicuro di voler cambiare da o a 'Impostazioni Per-Personaggio'?"
	TukuiConfigUILocalization.option_makeselection = "Devi seleziona un opzione prima di poter continuare la configurazione."
end