if GetLocale() == "koKR" then
	-- general
	TukuiConfigUILocalization.general = "일반"
	TukuiConfigUILocalization.generalautoscale = "자동으로 UI크기를 조절"
	TukuiConfigUILocalization.generaloverridelowtohigh = "저해상도에서 고해상도 버전의 개체창을 사용"
	TukuiConfigUILocalization.generalmultisampleprotect = "멀티샘플링을 항상 1배로 유지 (깨끗한 선)"
	TukuiConfigUILocalization.generaluiscale = "UI크기 (autoscale이 꺼져 있을 때)"
	TukuiConfigUILocalization.generalbackdropcolor = "판넬 기본 배경 색상 설정"
	TukuiConfigUILocalization.generalbordercolor = "판넬 기본 테두리 색상 설정"
	TukuiConfigUILocalization.generalblizzardreskin = "블리자드 기본 프레임을 Tukui에 맞게 조절합니다."
	 
	-- nameplate
	TukuiConfigUILocalization.nameplate = "이름표"
	TukuiConfigUILocalization.nameplateenable = "이름표를 사용"
	TukuiConfigUILocalization.nameplateenhancethreat = "위협수준 기능 사용, 당신의 역할에 따라 자동적으로 변경됨"
	TukuiConfigUILocalization.nameplateshowhealth = "생명력을 표시"
	TukuiConfigUILocalization.nameplatecombat = "전투 중에만 표시"
	TukuiConfigUILocalization.nameplategoodcolor = "해당 직업에게 좋은 색깔을 표시합니다. 탱커의 경우는 어그로를 잡았을때, 힐/딜은 반대"
	TukuiConfigUILocalization.nameplatebadcolor = "해당 직업에게 해로운 위협수준을 표시합니다."
	TukuiConfigUILocalization.nameplatetransitioncolor = "위협수준을 일정 수준으로 먹거나 잃을 때 표시"
	 
	-- merchant
	TukuiConfigUILocalization.merchant = "상점"
	TukuiConfigUILocalization.merchantsellgrays = "회색 아이템의 자동판매를 사용"
	TukuiConfigUILocalization.merchantautorepair = "자동수리를 사용"
	TukuiConfigUILocalization.merchantsellmisc = "회색이 아닌 잡템을 자동으로 판매합니다."
	 
	-- bags
	TukuiConfigUILocalization.bags = "가방"
	TukuiConfigUILocalization.bagsenable = "단일가방을 사용"
	 
	-- datatext
	TukuiConfigUILocalization.datatext = "정보 글자"
	TukuiConfigUILocalization.datatexttime24 = "24시 주기로 시간을 설정"
	TukuiConfigUILocalization.datatextlocaltime = "서버시간이 아닌 지역시간으로 설정"
	TukuiConfigUILocalization.datatextbattleground = "전장정보를 보여줌"
	TukuiConfigUILocalization.datatexthps_text = "초당 힐량 (0이면 미사용)"
	TukuiConfigUILocalization.datatextguild = "접속중인 길드원의 수 (0이면 미사용)"
	TukuiConfigUILocalization.datatext_arp = "방어구 관통 (0이면 미사용)"
	TukuiConfigUILocalization.datatextsystem = "메모리 사용량 (0이면 미사용)"
	TukuiConfigUILocalization.datatextbags = "소지품 여유 공간 (0이면 미사용)"
	TukuiConfigUILocalization.datatextfontsize = "텍스트 사이즈"
	TukuiConfigUILocalization.datatextfps_ms = "초당 프레임 수와 지연시간 (0이면 미사용)"
	TukuiConfigUILocalization.datatextarmor = "동일 레벨 대상에 의한 플레이어의 방어도 (0이면 미사용)"
	TukuiConfigUILocalization.datatextavd = "회피율 (0이면 미사용)"
	TukuiConfigUILocalization.datatextpower = "전투력,주문력,주문치유력,원거리 전투력중에 가장 높은 것 (0이면 미사용)"
	TukuiConfigUILocalization.datatexthaste = "가속도 (0이면 미사용)"
	TukuiConfigUILocalization.datatextfriends = "접속중인 친구 (0이면 미사용)"
	TukuiConfigUILocalization.datatextwowtime = "시간 (0이면 미사용)"
	TukuiConfigUILocalization.datatextgold = "보유중인 골드 (0이면 미사용)"
	TukuiConfigUILocalization.datatextdps_text = "초당 피해량 (0이면 미사용)"
	TukuiConfigUILocalization.datatextcrit = "치명타 및 주문 극대화 적중도 (0이면 미사용)"
	TukuiConfigUILocalization.datatextdur = "방어구 내구도 (0이면 미사용)"
	TukuiConfigUILocalization.datatextcurrency = "화폐 위치 (0이면 미사용)"
	TukuiConfigUILocalization.datatextmicromenu = "마이크로 메뉴 위치 (0이면 미사용)"
	TukuiConfigUILocalization.datatexthit = "적중도  (0이면 미사용)"
	TukuiConfigUILocalization.datatextmastery = "특화력 (0이면 미사용)"
	TukuiConfigUILocalization.datatexttalent = "현재 특성을 보여줍니다 (0이면 미사용)"
	TukuiConfigUILocalization.datatextcalltoarms = "전장신청 또는 무작위 던전 신청 (0이면 미사용)"

	 
	-- unit frames
	TukuiConfigUILocalization.unitframes = "개체창"
	TukuiConfigUILocalization.unitframescombatfeedback = "플레이어창과 대상창에 받는 피해량 및 치유량을 보여줌"
	TukuiConfigUILocalization.unitframesrunebar = "죽음의 기사 룬바를 사용"
	TukuiConfigUILocalization.unitframesauratimer = "강화 및 약화 효과의 지속시간 타이머를 사용"
	TukuiConfigUILocalization.unitframestotembar = "주술사 토템 타이머를 사용"
	TukuiConfigUILocalization.unitframesshowtotalhpmp = "체력과 마나를 '현재/전체'로 보여줌"
	TukuiConfigUILocalization.unitframesshowplayerinparty = "파티창에 자신을 보여줌"
	TukuiConfigUILocalization.unitframesraidunitdebuffwatch = "레이드시 디버프를 보여줍니다(격자모양 전용)"
	TukuiConfigUILocalization.unitframesunitcastbar = "시전 바 활성화"
	TukuiConfigUILocalization.unitframestargetauras = "현재 대상의 버프와 디버프 표시"
	TukuiConfigUILocalization.unitframessaveperchar = "개체창의 위치를 캐릭터마다 별도로 저장"
	TukuiConfigUILocalization.unitframesplayeraggro = "위협수준이 증가하면 강조"
	TukuiConfigUILocalization.unitframesshowsmooth = "부드러운 바를 사용"
	TukuiConfigUILocalization.unitframescharportrait = "플레이어와 대상의 초상화를 보여줌"
	TukuiConfigUILocalization.unitframesenable = "Tukui 개체창을 사용"
	TukuiConfigUILocalization.unitframestargetpowerpvponly =  "PVP대상만 분노, 기력 등의 글자를 보여줌"
	TukuiConfigUILocalization.unitframesgridonly =  "힐러용 인터페이스일 때 격자모양으로 설정"
	TukuiConfigUILocalization.unitframeshealcomm = "Healcomm 기능을 사용"
	TukuiConfigUILocalization.unitframesfocusdebuff = "주시대상의 약화 효과를 보여줌"
	TukuiConfigUILocalization.unitframesaggro = "위협수준이 높은 공격대원을 강조"
	TukuiConfigUILocalization.unitframesshowboss = "우두머리 개체창을 사용"
	TukuiConfigUILocalization.unitframesenemyhcolor = "적대감에 의존한 대상창 바의 색을 사용"
	TukuiConfigUILocalization.unitframesgridhealthvertical = "힐러용 인터페이스일 때 체력이 세로로 줄어듬"
	TukuiConfigUILocalization.unitframesshowsymbols = "공격대 인터페이스에 전술 목표 아이콘을 보여줌"
	TukuiConfigUILocalization.unitframesthreatbar = "위협수준 바를 사용"
	TukuiConfigUILocalization.unitframesshowrange = "공격대 인터페이스에 거리에 따른 투명도를 사용"
	TukuiConfigUILocalization.unitframesfocus = "주시대상의 대상을 보여줌"
	TukuiConfigUILocalization.unitframescblatency = "시전바에 지연시간을 보여줌"
	TukuiConfigUILocalization.unitframescbicons = "시전바에 아이콘을 보여줌"
	TukuiConfigUILocalization.unitframesplayerauras = "플레이어창 위에 강화 및 약화 효과를 보여줌"
	TukuiConfigUILocalization.unitframesauratextscale = "강화 및 약화 효과 지속시간의 글꼴크기"
	TukuiConfigUILocalization.unitframesgridscale = "공격대 인터페이스의 크기"
	TukuiConfigUILocalization.unitframesmanahigh = "마나가 높으면 경고를 보여줌 (사냥꾼 전용)"
	TukuiConfigUILocalization.unitframeslowThreshold = "마나가 낮으면 경고를 보여줌"
	TukuiConfigUILocalization.unitframesraidalphaoor = "거리에 따른 투명도 수치"
	TukuiConfigUILocalization.unitframesmaintank = "방어 전담창을 사용"
	TukuiConfigUILocalization.unitframesmainassist = "지원공격 전담창을 사용"
	TukuiConfigUILocalization.unitframesunicolor = "직업색상을 사용(회색 바)"
	TukuiConfigUILocalization.unitframestotdebuffs = "대상의 대상의 약화 효과를 보여줌 (고해상도 전용)"
	TukuiConfigUILocalization.unitframesclassbar = "직업 바 사용"
	TukuiConfigUILocalization.unitframesweakenedsoulbar = "약화된 영혼 알림바 사용 (사제)"
	TukuiConfigUILocalization.unitframesonlyselfdebuffs = "공격대/파티의 디버프만 대상창에 표시"
	TukuiConfigUILocalization.unitframesshowfocustarget = "주시대상의 대상을 보여줌"
	TukuiConfigUILocalization.unitframesbordercolor = "유닛프레임 기본 테두리 색상 설정"
	TukuiConfigUILocalization.unitframesmovecombobar = "대상 콤보 막대를 이동 (ROGUE ONLY)"
	TukuiConfigUILocalization.unitframesclassiccombo = "고전 콤보 포인트를 사용"
	TukuiConfigUILocalization.unitframesgridvertical = "그리드 수직에서 RAID 그룹을 표시합니다"
	TukuiConfigUILocalization.unitframesraid = "Enable Tukui Raid Frames"
	TukuiConfigUILocalization.unitframesshowraidpets = "Show Pets in Tukui Raid Frames"
	TukuiConfigUILocalization.unitframesdruidmanabar = "Show Druid Mana Bar in Bear/Cat form"
	TukuiConfigUILocalization.unitframesdruidmushroombar = "Show Druid Mushroom bar in Balance or Restoration specialization"
	TukuiConfigUILocalization.unitframesmageclassbar = "Show Mage Arcane Bar"
	TukuiConfigUILocalization.unitframesraidunitspercolumn = "Number of raid units per column/row"
	 
	-- loot
	TukuiConfigUILocalization.loot = "전리품"
	TukuiConfigUILocalization.lootlootframe = "전리품 획득창을 사용"
	TukuiConfigUILocalization.lootautogreed = "만렙일 때 자동차비 또는 자동마출을 사용"
	TukuiConfigUILocalization.lootrolllootframe = "주사위창을 사용"
	 
	-- invite
	TukuiConfigUILocalization.invite = "파티 초대"
	TukuiConfigUILocalization.inviteautoaccept = "길드원이나 친구에게서 온 초대에 대한 자동수락을 사용"
	 
	-- tooltip
	TukuiConfigUILocalization.tooltip = "툴팁"
	TukuiConfigUILocalization.tooltipenable = "툴팁 사용"
	TukuiConfigUILocalization.tooltiphidecombat = "전투시 툴팁을 숨김"
	TukuiConfigUILocalization.tooltiphidebuttons = "행동 단축버튼의 툴팁을 숨김"
	TukuiConfigUILocalization.tooltiphideuf = "개체창의 툴팁을 숨김"
	TukuiConfigUILocalization.tooltipcursor = "커서 툴팁 사용"
	 
	-- error
	TukuiConfigUILocalization.error = "에러 메세지"
	TukuiConfigUILocalization.errorenable = "화면 중앙의 오류메세지를 숨김"
	 
	-- action bar
	TukuiConfigUILocalization.actionbar = "행동 단축바"
	TukuiConfigUILocalization.actionbarhideshapeshift = "특수 기술 단축바 숨기기"
	TukuiConfigUILocalization.actionbarshowgrid = "빈 행동 단축버튼을 보여줌"
	TukuiConfigUILocalization.actionbarenable = "Tukui 행동 단축바를 사용"
	TukuiConfigUILocalization.actionbarrb = "우측측 바를 커서가 위치했을 때 보여줌"
	TukuiConfigUILocalization.actionbarhotkey = "행동 단축바에 단축키를 보여줌"
	TukuiConfigUILocalization.actionbarssmo = "특수 기술 단축바를 커서가 위치했을 때 보여줌"
	TukuiConfigUILocalization.actionbarrbn = "하단 단축바의 줄의 수 (1 또는 2)"
	TukuiConfigUILocalization.actionbarrn = "우측 단축바의 줄의 수 (0부터 3까지, 하단 단축바의 줄의 수가 2인 경우 0 또는 1)"
	TukuiConfigUILocalization.actionbarbuttonsize = "행동 단축버튼의 크기"
	TukuiConfigUILocalization.actionbarbuttonspacing = "행동 단축버튼의 간격"
	TukuiConfigUILocalization.actionbarpetbuttonsize = "펫/태세 버튼의 크기"
	TukuiConfigUILocalization.actionbarownshdbar = "도적이 어둠의 춤을 사용시 은신 단축바를 띄우지 않고 다른 바를 띄움"
	TukuiConfigUILocalization.actionbarownmetabar = "Use an empty bar for Metamorphosis (warlock) instead of main bar"
	TukuiConfigUILocalization.actionbarownwarstancebar = "Use an empty bar for each stance (warrior) instead of main bar"
	TukuiConfigUILocalization.actionbarmacro = "Show macro text on action bar"
	 
	-- arena
	TukuiConfigUILocalization.arena = "투기장"
	TukuiConfigUILocalization.unitframesarena = "투기장 상대 플레이어창을 사용 (Tukui 개체창을 사용 중이어야 함)"
	 
	-- cooldowns
	TukuiConfigUILocalization.cooldown = "재사용 대기시간"
	TukuiConfigUILocalization.cooldownenable = "재사용 대기시간 문자를 보여줌"
	TukuiConfigUILocalization.cooldowntreshold = "몇 초 아래로 내려갔을 때 글자가 빨간색으로 변하고 소수점 이하도 보여줄지 설정"
	 
	-- chat
	TukuiConfigUILocalization.chat = "커뮤니티"
	TukuiConfigUILocalization.chatenable = "Tukui 대화창 기능 사용"
	TukuiConfigUILocalization.chatwhispersound = "귓속말을 받았을때 소리 출력 "
	TukuiConfigUILocalization.chatbackground = "채팅 배경 사용"

	-- buff
	TukuiConfigUILocalization.auras = "강화 및 약화 효과"
	TukuiConfigUILocalization.aurasplayer = "Tukui 버프/디버프 창 사용"
	TukuiConfigUILocalization.aurasconsolidate = "일정 버프 통합 숨기기 사용"
	TukuiConfigUILocalization.aurasflash = "효과 지속시간이 30초이하로 남을 시 화면 번뜩임"
	TukuiConfigUILocalization.aurasclassictimer = "Display classic timer on player auras"

	-- buttons
	TukuiConfigUILocalization.option_button_reset = "초기화"
	TukuiConfigUILocalization.option_button_load = "불러오기"
	TukuiConfigUILocalization.option_button_close = "닫기"
	TukuiConfigUILocalization.option_setsavedsetttings = "캐릭터별로 저장"
	TukuiConfigUILocalization.option_resetchar = "해당 캐릭터의 설정을 기본 설정으로 초기화하시겠습니까?"
	TukuiConfigUILocalization.option_resetall = "모든 캐릭터의 설정을 기본 설정으로 초기화하시겠습니까?"
	TukuiConfigUILocalization.option_perchar = "설정을 캐릭터별로 저장하시겠습니까?"
	TukuiConfigUILocalization.option_makeselection = "계속하기전에 선택을 해야합니다."
end