if GetLocale() == "ptBR" then
	-- translated by kurhyus

	-- general
	TukuiConfigUILocalization.general = "Geral"
	TukuiConfigUILocalization.generalautoscale = "Escala da UI Automática"
	TukuiConfigUILocalization.generaloverridelowtohigh = "Use um layout de alta resolução numa resolução baixa"
	TukuiConfigUILocalization.generalmultisampleprotect = "Protecção Multiamostragens (Rebordo limpo 1px)"
	TukuiConfigUILocalization.generaluiscale = "Escala da UI (se a escala da UI automática estiver desactiva)"
	TukuiConfigUILocalization.generalbackdropcolor = "Define a cor padrão do fundo para os painéis" 
	TukuiConfigUILocalization.generalbordercolor = "Define a cor padrão do rebordo dos painéis"
	TukuiConfigUILocalization.generalblizzardreskin = "Redesenha dos quadros da Blizzard para condizer com a Tukui" 
	 
	-- nameplate
	TukuiConfigUILocalization.nameplate = "Placas de Identificação"
	TukuiConfigUILocalization.nameplateenable = "Activar Placas de Identificação"
	TukuiConfigUILocalization.nameplateenhancethreat = "Activar a opção de 'Ameaça', muda automáticamente conforme o seu papel"
	TukuiConfigUILocalization.nameplateshowhealth = "Mostrar vida na Placa de Identificação"
	TukuiConfigUILocalization.nameplatecombat = "Em combate, apenas mostrar as placas de identificação do inimigo"
	TukuiConfigUILocalization.nameplategoodcolor = "Cor de ameaça boa, varia dependendo de você ser um tank ou um dps/cura"
	TukuiConfigUILocalization.nameplatebadcolor = "Cor de ameaça má, varia dependendo de você ser um tank ou um dps/cura"
	TukuiConfigUILocalization.nameplatetransitioncolor = "Perdendo/Ganhando cor de Ameaça"
	 
	-- merchant
	TukuiConfigUILocalization.merchant = "Vendedor"
	TukuiConfigUILocalization.merchantsellgrays = "Vender itens cinzentos automaticamente"
	TukuiConfigUILocalization.merchantautorepair = "Reparar itens automaticamente"
	TukuiConfigUILocalization.merchantsellmisc = "Vender alguns itens definidos (Lixo não cinzento) automaticamente" 
	 
	-- bags
	TukuiConfigUILocalization.bags = "Sacos"
	TukuiConfigUILocalization.bagsenable = "Activar Sacos tudo-em-um"
	 
	-- datatext
	TukuiConfigUILocalization.datatext = "Texto de dados"
	TukuiConfigUILocalization.datatexttime24 = "Activar formato de 24 horas"
	TukuiConfigUILocalization.datatextlocaltime = "Usar hora local em vez da hora do servidor"
	TukuiConfigUILocalization.datatextbattleground = "Activar status do Campo de Batalha"
	TukuiConfigUILocalization.datatexthps_text = "Posição da Cura Por Segundo (0 para desactivar)"
	TukuiConfigUILocalization.datatextguild = "Posição da Guilda (0 para desactivar)"
	TukuiConfigUILocalization.datatext_arp = "Posição da Penetração de Armadura (0 para desactivar)"
	TukuiConfigUILocalization.datatextsystem = "Posição da Memória (0 para desactivar)"
	TukuiConfigUILocalization.datatextbags = "Posição dos Sacos (0 para desactivar)"
	TukuiConfigUILocalization.datatextfontsize = "Tamanho da fonte do texto"
	TukuiConfigUILocalization.datatextfps_ms = "Posição da Latência e dos FPS (0 para desactivar)"
	TukuiConfigUILocalization.datatextarmor = "Posição da Armadura (0 para desactivar)"
	TukuiConfigUILocalization.datatextavd = "Posição da Evasão (0 para desactivar)"
	TukuiConfigUILocalization.datatextpower = "Posição do Poder (0 para desactivar)"
	TukuiConfigUILocalization.datatexthaste = "Posição da Aceleração (0 para desactivar)"
	TukuiConfigUILocalization.datatextfriends = "Posição dos Amigos (0 para desactivar)"
	TukuiConfigUILocalization.datatextwowtime = "Posição da Hora (0 para desactivar)"
	TukuiConfigUILocalization.datatextgold = "Posição do Ouro (0 para desactivar)"
	TukuiConfigUILocalization.datatextdps_text = "Posição do Dano Por Segundo (0 para desactivar)"
	TukuiConfigUILocalization.datatextcrit = "Posição da % de Crítico (0 para desactivar)"
	TukuiConfigUILocalization.datatextdur = "Posição da Durabilidade (0 para desactivar)"
	TukuiConfigUILocalization.datatextcurrency = "Posição da Moeda de Troca (0 para desactivar)"
	TukuiConfigUILocalization.datatextmicromenu = "Posição do Micro Menu (0 para desactivar)"
	TukuiConfigUILocalization.datatexthit = "Posição do Acerto (0 para desactivar)"
	TukuiConfigUILocalization.datatextmastery = "Posição da Maestria (0 para desactivar)"
	TukuiConfigUILocalization.datatexttalent = " Mostrar Talentos (0 para desactivar)"
	TukuiConfigUILocalization.datatextcalltoarms = "Chamado às Armas & Masmorras (0 para desactivar)"
	TukuiConfigUILocalization.unitframesmovecombobar = " Mover a barra de combos do alvo (APENAS PARA LADINOS (ROGUES))"
	TukuiConfigUILocalization.unitframesclassiccombo = "Usar ponto clássico de combos"
	TukuiConfigUILocalization.unitframesgridvertical = "Mostrar grupos de raide Verticalmente na Grelha"

	 
	-- unit frames
	TukuiConfigUILocalization.unitframes = "Quadros de Unidades"
	TukuiConfigUILocalization.unitframescombatfeedback = "Comentários de combate sobre o jogador e o alvo"
	TukuiConfigUILocalization.unitframesrunebar = "Activar barra de runas para Cavaleiro da Morte"
	TukuiConfigUILocalization.unitframesauratimer = "Activar temporizador das auras"
	TukuiConfigUILocalization.unitframestotembar = "Activar barra de totems para Xamã"
	TukuiConfigUILocalization.unitframesshowtotalhpmp = "Mostrar vida/poder total"
	TukuiConfigUILocalization.unitframesshowplayerinparty = "Mostrar o jogador no grupo"
	TukuiConfigUILocalization.unitframesraidunitdebuffwatch = "Activar o Observador de Auras em raide PVE (Apenas para a Grelha)"
	TukuiConfigUILocalization.unitframesunitcastbar = "Activar Barra de Lançamento"
	TukuiConfigUILocalization.unitframestargetauras = "Activar Auras dos Alvos"
	TukuiConfigUILocalization.unitframessaveperchar = "Salvar quadros de unidades por cada personagem"
	TukuiConfigUILocalization.unitframesplayeraggro = "Activar mostrador de agro em si próprio"
	TukuiConfigUILocalization.unitframesshowsmooth = "Activar barra lisa"
	TukuiConfigUILocalization.unitframescharportrait = "Activar retrato do jogador e do alvo"
	TukuiConfigUILocalization.unitframesenable = "Activar quadros de unidades da Tukui"
	TukuiConfigUILocalization.unitframestargetpowerpvponly = "Activar mostrador de poder apenas do inimigo"
	TukuiConfigUILocalization.unitframesgridonly = "Activar o modo de Grelha apenas para o layout de curandeiro"
	TukuiConfigUILocalization.unitframeshealcomm = "Activar cura por vir"
	TukuiConfigUILocalization.unitframesfocusdebuff = "Activar debuffs do Foco"
	TukuiConfigUILocalization.unitframesaggro = "Activar mostrador de agro no grupo/raide"
	TukuiConfigUILocalization.unitframesshowboss = "Activar quadros de unidades dos Chefes"
	TukuiConfigUILocalization.unitframesenemyhcolor = "Colorir barra de vida do inimigo por hostilidade (para PVP)"
	TukuiConfigUILocalization.unitframesgridhealthvertical = "Mostrar barra de vida verticalmente para o layout da Grelha"
	TukuiConfigUILocalization.unitframesshowsymbols = "Mostrar símbolos no grupo/raide"
	TukuiConfigUILocalization.unitframesthreatbar = "Activar barra de ameaça"
	TukuiConfigUILocalization.unitframesshowrange = "Activar mostrador de distância para o grupo/raide"
	TukuiConfigUILocalization.unitframesfocus = "Activar alvo do Foco"
	TukuiConfigUILocalization.unitframescblatency = "Mostrar latência na barra de lançamento"
	TukuiConfigUILocalization.unitframescbicons = "Mostrar icons na barra de lançamento"
	TukuiConfigUILocalization.unitframesplayerauras = "Activa um modo de auras alternativo para o jogador"
	TukuiConfigUILocalization.unitframesauratextscale = "Escala do texto de auras nas auras"
	TukuiConfigUILocalization.unitframesgridscale = "Escala da Grelha"
	TukuiConfigUILocalization.unitframesmanahigh = "Indicador de mana alta (Para Caçador)"
	TukuiConfigUILocalization.unitframeslowThreshold = "Indicador de mana baixa (para todas as classes que usam mana)"
	TukuiConfigUILocalization.unitframesraidalphaoor = "Transparência no grupo/raide quando fora de alcance"
	TukuiConfigUILocalization.unitframesmaintank = "Activar Tank Principal"
	TukuiConfigUILocalization.unitframesmainassist = "Activar Assistente Principal"
	TukuiConfigUILocalization.unitframesunicolor = "Activar Tema de cor única (barra de vida cinzenta)"
	TukuiConfigUILocalization.unitframestotdebuffs = "Activar debuffs do Alvo do Alvo (alta resolução)"
	TukuiConfigUILocalization.unitframesclassbar = "Activar barra da Classe"
	TukuiConfigUILocalization.unitframesweakenedsoulbar = "Activar notificação da barra do debuff Alma Enfraquecida (Sacerdotes)"
	TukuiConfigUILocalization.unitframesonlyselfdebuffs = "Mostrar apenas os seus debuffs no alvo"
	TukuiConfigUILocalization.unitframesshowfocustarget = "Activar alvo do Foco"
	TukuiConfigUILocalization.unitframesbordercolor = "Definir cor padrão das bordas dos painéis"
	TukuiConfigUILocalization.unitframesraid = "Activar Quadros de Raide da Tuikui"
	TukuiConfigUILocalization.unitframesshowraidpets = "Mostrar ajudantes nos quadros de raide da Tukui"
	TukuiConfigUILocalization.unitframesdruidmanabar = "Mostrar a barra de mana do Druida estando em forma de Urso/gato"
	TukuiConfigUILocalization.unitframesdruidmushroombar = "Mostrar barra de Cogumelo do Druida estando em especialização de Equilíbrio ou de Restauração"
	TukuiConfigUILocalization.unitframesmageclassbar = "Mostrar barra de Arcano do Mago"
	TukuiConfigUILocalization.unitframesraidunitspercolumn = "Número de unidades de raide por coluna/Linha"
	TukuiConfigUILocalization.unitframesmaxraidplayers = "Max raid frames displayed according to instance max players"
	 
	-- loot
	TukuiConfigUILocalization.loot = "Saque"
	TukuiConfigUILocalization.lootlootframe = "Activar janela de Saque"
	TukuiConfigUILocalization.lootautogreed = "Activar ganância automática para itens verdes no nível máximo" 
	TukuiConfigUILocalization.lootrolllootframe = "Activar janela de rolar itens"
	 
	-- invite
	TukuiConfigUILocalization.invite = "Convidar"
	TukuiConfigUILocalization.inviteautoaccept = "Activar convite automático (Amigos e colegas da guilda)"
	 
	-- tooltip
	TukuiConfigUILocalization.tooltip = "Tooltip"
	TukuiConfigUILocalization.tooltipenable = "Activar a tooltip"
	TukuiConfigUILocalization.tooltiphidecombat = "Esconder a tooltip em combate"
	TukuiConfigUILocalization.tooltiphidebuttons = "Esconder a tooltip nos botões das barras de acção"
	TukuiConfigUILocalization.tooltiphideuf = "Esconder a tooltip nos quadros de unidades"
	TukuiConfigUILocalization.tooltipcursor = "Activar o cursor da tooltip"
	 
	-- error
	TukuiConfigUILocalization.error = "Mensagem de Erro"
	TukuiConfigUILocalization.errorenable = "Ocultar spam de erros no meio da seu ecrã"
	 
	-- action bar
	TukuiConfigUILocalization.actionbar = "Barras de Acção"
	TukuiConfigUILocalization.actionbarhideshapeshift = "Ocultar barra de mudança de forma ou barra dos totems"
	TukuiConfigUILocalization.actionbarshowgrid = "Mostrar sempre a grelha nas barras de acção" 
	TukuiConfigUILocalization.actionbarenable = "Activar barras de acção da Tukui"
	TukuiConfigUILocalization.actionbarrb = "Activar barra direita ao passar sobre ela com o rato"
	TukuiConfigUILocalization.actionbarhotkey = "Mostrar Tecla rápida nos botões"
	TukuiConfigUILocalization.actionbarssmo = "Mostrar Barra de mudança de forma ou barra de totems ao passar sobre ela com o rato"
	TukuiConfigUILocalization.actionbarrbn = "Número de barras de acção em baixo (1 ou 2)"
	TukuiConfigUILocalization.actionbarrn = "Número de barras de acção na direita (0, 1, 2, ou 3)"
	TukuiConfigUILocalization.actionbarbuttonsize = "Tamanho dos botões de acção principais" 
	TukuiConfigUILocalization.actionbarbuttonspacing = "Espaçamento dos botões de acção principais"
	TukuiConfigUILocalization.actionbarpetbuttonsize = "Tamanho dos botões do ajudante/Mudança de Forma"
	TukuiConfigUILocalization.actionbarownshdbar = "Usar uma barra vazia para a dança da sombra (ladino) em vez de usar a barra Furtiva"
	TukuiConfigUILocalization.actionbarownmetabar = "Usar uma barra vazia para a Metamorfose (Bruxo) em vez de usar a barra principal"
	TukuiConfigUILocalization.actionbarownwarstancebar = "Usar uma barra vazia para cada postura (Guerreiro) em vez de usar a barra principal"
	TukuiConfigUILocalization.actionbarmacro = "Mostrar o texto das macros nas barras de acção"
	 
	-- arena
	TukuiConfigUILocalization.arena = "Arena"
	TukuiConfigUILocalization.unitframesarena = "Activar quadros de unidades de Arena"
	 
	-- cooldowns
	TukuiConfigUILocalization.cooldown = "Tempo de Recarga"
	TukuiConfigUILocalization.cooldownenable = "Activar o tempo de recarga nos botões"
	TukuiConfigUILocalization.cooldowntreshold = "Mudar o tempo de recarga para vermelho a valor X"
	 
	-- chat
	TukuiConfigUILocalization.chat = "Conversação"
	TukuiConfigUILocalization.chatenable = "Activar conversação da Tukui"
	TukuiConfigUILocalization.chatwhispersound = "Reproduzir som ao receber uma mensagem privada"
	TukuiConfigUILocalization.chatbackground = "Activar painel de fundo de Conversação"

	-- buff
	TukuiConfigUILocalization.auras = "Auras"
	TukuiConfigUILocalization.aurasplayer = "Activar os quadros de Buffs/Debuffs da Tukui"
	TukuiConfigUILocalization.aurasconsolidate = "Activar consolidação de Buffs"
	TukuiConfigUILocalization.aurasflash = "Activar Piscar nas auras com menos de 30 segundos"
	TukuiConfigUILocalization.aurasclassictimer = "Mostrar no modo clássico o temporizador das auras do jogador"

	-- buttons
	TukuiConfigUILocalization.option_button_reset = "Restaurar"
	TukuiConfigUILocalization.option_button_load = "Aplicar Definições"
	TukuiConfigUILocalization.option_button_close = "Fechar"
	TukuiConfigUILocalization.option_setsavedsetttings = "Estabelecer definições por personagem"
	TukuiConfigUILocalization.option_resetchar = "Tem a certeza que quer restaurar as definições do seu personagem para condizerem com suas definições padrão?"
	TukuiConfigUILocalization.option_resetall = "Tem a certeza que quer restaurar todas as definições para o modo padrão?"
	TukuiConfigUILocalization.option_perchar = "Tem certeza que quer mudar de ou para 'Definições por personagem'?"
	TukuiConfigUILocalization.option_makeselection = "Você tem de fazer uma escolha antes de puder continuar a configurar."
end