if GetLocale() == "ruRU" then
	-- translated by Wetxius, special thanks Shestak

	-- general
	TukuiConfigUILocalization.general = "Общее"
	TukuiConfigUILocalization.generalautoscale = "Автоматически масштабировать интерфейс"
	TukuiConfigUILocalization.generaloverridelowtohigh = "Использовать высокое разрешение на мониторах низкого разрешения"
	TukuiConfigUILocalization.generalmultisampleprotect = "1-разр. сглаживание (ровные края шириной 1 пиксель)"
	TukuiConfigUILocalization.generaluiscale = "Масштаб интерфейса (если автоматическое масштабирование отключено)"
	TukuiConfigUILocalization.generalbackdropcolor = "Установить цвет фона панелей"
	TukuiConfigUILocalization.generalbordercolor = "Установить цвет границы панелей"
	TukuiConfigUILocalization.generalblizzardreskin = "Включить стилизацию элементов интерфейса Blizzard"
	 
	-- nameplate
	TukuiConfigUILocalization.nameplate = "Индикаторы здоровья"
	TukuiConfigUILocalization.nameplateenable = "Включить индикаторы здоровья"
	TukuiConfigUILocalization.nameplateenhancethreat = "Автоматическая смена цвета угрозы (зависит от вашей роли)"
	TukuiConfigUILocalization.nameplateshowhealth = "Цифровое значение здоровья"
	TukuiConfigUILocalization.nameplatecombat = "Показывать индикаторы только во время боя"
	TukuiConfigUILocalization.nameplategoodcolor = "Цвет наименьшей угрозы, зависит от вашей роли"
	TukuiConfigUILocalization.nameplatebadcolor = "Цвет наивысшей угрозы, зависит от вашей роли"
	TukuiConfigUILocalization.nameplatetransitioncolor = "Цвет получения/сброса угрозы"
	 
	-- merchant
	TukuiConfigUILocalization.merchant = "Торговля"
	TukuiConfigUILocalization.merchantsellgrays = "Автоматически продавать серые вещи"
	TukuiConfigUILocalization.merchantautorepair = "Автоматически ремонтировать вещи"
	TukuiConfigUILocalization.merchantsellmisc = "Продавать кое-какой хлам (не серый) автоматически"
	 
	-- bags
	TukuiConfigUILocalization.bags = "Сумки"
	TukuiConfigUILocalization.bagsenable = "Включить единую сумку"
	 
	-- datatext
	TukuiConfigUILocalization.datatext = "Статистика"
	TukuiConfigUILocalization.datatexttime24 = "Включить 24ч время"
	TukuiConfigUILocalization.datatextlocaltime = "Использовать местное время, а не серверное"
	TukuiConfigUILocalization.datatextbattleground = "Включить статистику на Поле Боя"
	TukuiConfigUILocalization.datatexthps_text = "Исцеление в секунду, позиция (0 для отключения)"
	TukuiConfigUILocalization.datatextguild = "Гильдия, позиция (0 для отключения)"
	TukuiConfigUILocalization.datatext_arp = "Пробивание брони, позиция (0 для отключения)"
	TukuiConfigUILocalization.datatextsystem = "Память, позиция (0 для отключения)"
	TukuiConfigUILocalization.datatextbags = "Сумки, позиция (0 для отключения)"
	TukuiConfigUILocalization.datatextfontsize = "Размер шрифта текста"
	TukuiConfigUILocalization.datatextfps_ms = "Задержка и FPS,  позиция ((0 для отключения)"
	TukuiConfigUILocalization.datatextarmor = "Броня, позиция (0 для отключения)"
	TukuiConfigUILocalization.datatextavd = "Авойданс, позиция (0 для отключения)"
	TukuiConfigUILocalization.datatextpower = "Энергия, позиция (0 для отключения)"
	TukuiConfigUILocalization.datatexthaste = "Скорость, позиция (0 для отключения)"
	TukuiConfigUILocalization.datatextfriends = "Друзья, позиция (0 для отключения)"
	TukuiConfigUILocalization.datatextwowtime = "Время, позиция (0 для отключения)"
	TukuiConfigUILocalization.datatextgold = "Золото, позиция (0 для отключения)"
	TukuiConfigUILocalization.datatextdps_text = "Урон в секунду, позиция (0 для отключения)"
	TukuiConfigUILocalization.datatextcrit = "Крит % , позиция (0 для отключения)"
	TukuiConfigUILocalization.datatextdur = "Прочность, позиция (0 для отключения)"
	TukuiConfigUILocalization.datatextcurrency = "Валюта,  позиция (0 для отключения)"
	TukuiConfigUILocalization.datatextmicromenu = "Микро меню,  позиция (0 для отключения)"
	TukuiConfigUILocalization.datatexthit = "Точность,  позиция (0 для отключения)"
	TukuiConfigUILocalization.datatextmastery = "Искуссность, позиция (0 для отключения)"
	TukuiConfigUILocalization.datatexttalent = "Таланты (0 для отключения)"
	TukuiConfigUILocalization.datatextcalltoarms = "Призыв к оружию & Подземелья (0 для отключения)"

	 
	-- unit frames
	TukuiConfigUILocalization.unitframes = "Рамки портретов"
	TukuiConfigUILocalization.unitframescombatfeedback = "Текст боя на рамках игрока и цели"
	TukuiConfigUILocalization.unitframesrunebar = "Включить индикатор рун для Рыцарей Смерти"
	TukuiConfigUILocalization.unitframesauratimer = "Отображать таймер перезарядки аур"
	TukuiConfigUILocalization.unitframestotembar = "Включить индикатор тотемов для Шаманов"
	TukuiConfigUILocalization.unitframesshowtotalhpmp = "Отображать общее здоровье/энергию"
	TukuiConfigUILocalization.unitframesshowplayerinparty = "Отображать рамку игрока в группе"
	TukuiConfigUILocalization.unitframesraidunitdebuffwatch = "Отображать отрицательные эффекты (Grid Only)"
	TukuiConfigUILocalization.unitframesunitcastbar = "Включить индикатор применения заклинаний"
	TukuiConfigUILocalization.unitframestargetauras = "Включить ауры цели"
	TukuiConfigUILocalization.unitframessaveperchar = "Сохранять позиции рамок только для персонажа"
	TukuiConfigUILocalization.unitframesplayeraggro = "Отображать свою угрозу"
	TukuiConfigUILocalization.unitframesshowsmooth = "Плавное изменение полос"
	TukuiConfigUILocalization.unitframescharportrait = "Отображать портреты игрока и цели"
	TukuiConfigUILocalization.unitframesenable = "Включить рамки портретов"
	TukuiConfigUILocalization.unitframestargetpowerpvponly = "Отображать значение энергии только на враге"
	TukuiConfigUILocalization.unitframesgridonly = "Включить Grid only для раскладки Целителей"
	TukuiConfigUILocalization.unitframeshealcomm = "Отображать поступающее лечение"
	TukuiConfigUILocalization.unitframesfocusdebuff = "Включить дебаффы фокуса"
	TukuiConfigUILocalization.unitframesaggro = "Включить отображение угрозы на рамках группы/рейда"
	TukuiConfigUILocalization.unitframesshowboss = "Отображать рамки боссов"
	TukuiConfigUILocalization.unitframesenemyhcolor = "Окрашивать полосу здоровья вражеского игрока по враждебности (для PVP)"
	TukuiConfigUILocalization.unitframesgridhealthvertical = "Показывать здоровье вертикально для Grid layout"
	TukuiConfigUILocalization.unitframesshowsymbols = "Показывать символы в группе/рейде"
	TukuiConfigUILocalization.unitframesthreatbar = "Включить панель угрозы"
	TukuiConfigUILocalization.unitframesshowrange = "Прозрачность рамок группы/рейда вне зоны досягаемости"
	TukuiConfigUILocalization.unitframesfocus = "Отображать рамку фокуса"
	TukuiConfigUILocalization.unitframescblatency = "Задержка заклинания на индикаторе"
	TukuiConfigUILocalization.unitframescbicons = "Иконка индикатора заклинания"
	TukuiConfigUILocalization.unitframesplayerauras = "Включить альтернативный показ аур для игрока"
	TukuiConfigUILocalization.unitframesauratextscale = "Размер текста на аурах"
	TukuiConfigUILocalization.unitframesgridscale = "Размер Grid"
	TukuiConfigUILocalization.unitframesmanahigh = "Индикатор избытка маны (Для охотников)"
	TukuiConfigUILocalization.unitframeslowThreshold = "Индикатор нехватки маны (Все классы с маной)"
	TukuiConfigUILocalization.unitframesraidalphaoor = "Значение для прозрачности рамок группы/рейда вне зоны досягаемости"
	TukuiConfigUILocalization.unitframesmaintank = "Отображать рамки танков рейда"
	TukuiConfigUILocalization.unitframesmainassist = "Отображать рамки помощников"
	TukuiConfigUILocalization.unitframesunicolor = "Включить особую цветовую схему (серая панель здоровья)"
	TukuiConfigUILocalization.unitframestotdebuffs = "Включить дебаффы цели цели (Высокое Разр.)"
	TukuiConfigUILocalization.unitframesclassbar = "Включить панель класса"
	TukuiConfigUILocalization.unitframesweakenedsoulbar = "Включить панель уведомления Ослабленной Души (Priest)"
	TukuiConfigUILocalization.unitframesonlyselfdebuffs = "Только ваши отрицательные эффекты на цели"
	TukuiConfigUILocalization.unitframesshowfocustarget = "Включить цель фокуса"
	TukuiConfigUILocalization.unitframesbordercolor = "Установить цвет границы панелей"
	TukuiConfigUILocalization.unitframesmovecombobar = "Передвинуть индикатор серии приемов(ТОЛЬКО ДЛЯ РАЗБОЙНИКОВ)"
	TukuiConfigUILocalization.unitframesclassiccombo = "Классический вид индикатора серий приемов"
	TukuiConfigUILocalization.unitframesgridvertical = "Группы рейда вертикально"
	TukuiConfigUILocalization.unitframesraid = "Включить рамки рейда Tukui"
	TukuiConfigUILocalization.unitframesshowraidpets = "Показывать питомцев в рамках рейда Tukui"
	TukuiConfigUILocalization.unitframesdruidmanabar = "Показывать полосу маны друида в формах медведя/кота"
	TukuiConfigUILocalization.unitframesdruidmushroombar = "Показывать индикатор грибов для друидов баланса и исцеления"
	TukuiConfigUILocalization.unitframesmageclassbar = "Отображать полосу чародейских зарядов мага"
	TukuiConfigUILocalization.unitframesraidunitspercolumn = "Количество рейдовых юнитов на ряд/столбец"
	TukuiConfigUILocalization.unitframesmaxraidplayers = "Max raid frames displayed according to instance max players"
	 
	-- loot
	TukuiConfigUILocalization.loot = "Добыча"
	TukuiConfigUILocalization.lootlootframe = "Включить окно добычи"
	TukuiConfigUILocalization.lootautogreed = "Автоматически нажимать *не откажусь* для зеленых предметов на максимальном уровне"
	TukuiConfigUILocalization.lootrolllootframe = "Включить групповое окно добычи"
	 
	-- invite
	TukuiConfigUILocalization.invite = "Приглашения"
	TukuiConfigUILocalization.inviteautoaccept = "Автоматическое принятие приглашений от друзей и гильдии"
	 
	-- tooltip
	TukuiConfigUILocalization.tooltip = "Подсказки"
	TukuiConfigUILocalization.tooltipenable = "Включить подсказки"
	TukuiConfigUILocalization.tooltiphidecombat = "Прятать подсказку в бою"
	TukuiConfigUILocalization.tooltiphidebuttons = "Прятать подсказку для кнопок панели действий"
	TukuiConfigUILocalization.tooltiphideuf = "Прятать подсказку для рамок портретов"
	TukuiConfigUILocalization.tooltipcursor = "Подсказка под указателем мыши"
	 
	-- error
	TukuiConfigUILocalization.error = "Ошибки"
	TukuiConfigUILocalization.errorenable = "Спрятать все ошибки посередине экрана"
	 
	-- action bar
	TukuiConfigUILocalization.actionbar = "Панели команд"
	TukuiConfigUILocalization.actionbarhideshapeshift = "Скрыть панель стоек/тотемов"
	TukuiConfigUILocalization.actionbarshowgrid = "Отображать пустые кнопки панелей команд"
	TukuiConfigUILocalization.actionbarenable = "Включить панели команд"
	TukuiConfigUILocalization.actionbarrb = "Правые панели команд по наведению курсора"
	TukuiConfigUILocalization.actionbarhotkey = "Отображать назначения клавиш"
	TukuiConfigUILocalization.actionbarssmo = "Панель стоек и тотемов по наведению курсора"
	TukuiConfigUILocalization.actionbarrbn = "Количество нижних панелей (1 или 2)"
	TukuiConfigUILocalization.actionbarrn = "Количество правых панелей (0, 1, 2 или 3)"
	TukuiConfigUILocalization.actionbarbuttonsize = "Размер кнопок панелей команд"
	TukuiConfigUILocalization.actionbarbuttonspacing = "Расстояние между кнопками"
	TukuiConfigUILocalization.actionbarpetbuttonsize = "Размер кнопок панели питомца/стоек"
	TukuiConfigUILocalization.actionbarownshdbar = "Использовать пустую панель для танца теней (разбойник) вместо панели невидимости"
	TukuiConfigUILocalization.actionbarownmetabar = "Использовать пустую панель для Метаморфозы чернокнижника вместо основной панели"
	TukuiConfigUILocalization.actionbarownwarstancebar = "Использовать пустую панель для каждой стойки (воин) вместо основной панели"
	TukuiConfigUILocalization.actionbarmacro = "Показывать названия макросов на панели команд"
	 
	-- arena
	TukuiConfigUILocalization.arena = "Арена"
	TukuiConfigUILocalization.unitframesarena = "Включить рамки портретов арены"
	 
	-- cooldowns
	TukuiConfigUILocalization.cooldown = "Перезарядки"
	TukuiConfigUILocalization.cooldownenable = "Отображать перезарядки на кнопках"
	TukuiConfigUILocalization.cooldowntreshold = "Задать значение перезарядки для показа в миллисекундах"
	 
	-- chat
	TukuiConfigUILocalization.chat = "Чат"
	TukuiConfigUILocalization.chatenable = "Включить чат"
	TukuiConfigUILocalization.chatwhispersound = "Звуковое оповещение во время шепота"
	TukuiConfigUILocalization.chatbackground = "Включить фон чата"

	-- buff
	TukuiConfigUILocalization.auras = "Ауры"
	TukuiConfigUILocalization.aurasplayer = "Включить Баффы/Дебаффы Tukui"
	TukuiConfigUILocalization.aurasconsolidate = "Объединить ауры"
	TukuiConfigUILocalization.aurasflash = "Включить анимацию мигания ауры на 30 секундах"
	TukuiConfigUILocalization.aurasclassictimer = "Использовать классические таймеры на аурах игрока"

	-- buttons
	TukuiConfigUILocalization.option_button_reset = "Сброс"
	TukuiConfigUILocalization.option_button_load = "Применить настройки"
	TukuiConfigUILocalization.option_button_close = "Закрыть"
	TukuiConfigUILocalization.option_setsavedsetttings = "Установить настройки для персонажа"
	TukuiConfigUILocalization.option_resetchar = "Вы уверены, что хотите сбросить все настройки для этого персонажа?"
	TukuiConfigUILocalization.option_resetall = "Вы уверены, что хотите сбросить все настройки?"
	TukuiConfigUILocalization.option_perchar = "Вы уверены, что хотите сменить режим сохранения настроек?"
	TukuiConfigUILocalization.option_makeselection = "Вы должны сделать выбор прежде чем продолжите конфигурацию."
end