if GetLocale() == "zhTW" then
	-- translated by ?

	-- general
	TukuiConfigUILocalization.general = "一般"
	TukuiConfigUILocalization.generalautoscale = "自動調整使用者介面比例"
	TukuiConfigUILocalization.generaloverridelowtohigh = "使用高解析度設定於低解析度"
	TukuiConfigUILocalization.generalmultisampleprotect = "多重採樣保護 (乾淨的 1px 邊框)"
	TukuiConfigUILocalization.generaluiscale = "使用者介面比例(需要關閉自動調整)"
	TukuiConfigUILocalization.generalbackdropcolor = "設定面板背景顏色"
	TukuiConfigUILocalization.generalbordercolor = "設定面板邊框顏色"
	TukuiConfigUILocalization.generalblizzardreskin = "使用Tukui樣式來美化暴雪框架"
	 
	-- nameplate
	TukuiConfigUILocalization.nameplate = "名條"
	TukuiConfigUILocalization.nameplateenable = "啟用名條模組"
	TukuiConfigUILocalization.nameplateenhancethreat = "啟用仇恨上色模式, 依照你的角色定位決定"
	TukuiConfigUILocalization.nameplateshowhealth = "在名條上顯示生命值"
	TukuiConfigUILocalization.nameplatecombat = "只在戰鬥中顯示敵人名條"
	TukuiConfigUILocalization.nameplategoodcolor = "安全仇恨值顏色, 將根據你的角色定位決定"
	TukuiConfigUILocalization.nameplatebadcolor = "危險威仇恨值顏色, 將根據你的角色定位決定"
	TukuiConfigUILocalization.nameplatetransitioncolor = "流失或獲得仇恨值顏色"
	 
	-- merchant
	TukuiConfigUILocalization.merchant = "商人"
	TukuiConfigUILocalization.merchantsellgrays = "自動販賣灰色等級物品"
	TukuiConfigUILocalization.merchantautorepair = "自動修復裝備"
	TukuiConfigUILocalization.merchantsellmisc = "自動販賣特定物品(非灰色等級的垃圾物品)"
	 
	-- bags
	TukuiConfigUILocalization.bags = "背包"
	TukuiConfigUILocalization.bagsenable = "啟用整合背包"
	 
	-- datatext
	TukuiConfigUILocalization.datatext = "資訊欄位"
	TukuiConfigUILocalization.datatexttime24 = "啟用24小時制"
	TukuiConfigUILocalization.datatextlocaltime = "使用當地時間"
	TukuiConfigUILocalization.datatextbattleground = "啟用戰場資訊 (輸入 0 以停用)"
	TukuiConfigUILocalization.datatexthps_text = "每秒治療 (輸入 0 以停用)"
	TukuiConfigUILocalization.datatextguild = "公會資訊 (輸入 0 以停用)"
	TukuiConfigUILocalization.datatext_arp = "護甲穿透 (輸入 0 以停用)"
	TukuiConfigUILocalization.datatextsystem = "記憶體用量 (輸入 0 以停用)"
	TukuiConfigUILocalization.datatextbags = "背包格數 (輸入 0 以停用)"
	TukuiConfigUILocalization.datatextfontsize = "文字大小 (輸入 0 以停用)"
	TukuiConfigUILocalization.datatextfps_ms = "延遲及畫面幀數 (輸入 0 以停用)"
	TukuiConfigUILocalization.datatextarmor = "護甲值 (輸入 0 以停用)"
	TukuiConfigUILocalization.datatextavd = "閃躲 (輸入 0 以停用)"
	TukuiConfigUILocalization.datatextpower = "攻強/法傷 (輸入 0 以停用)"
	TukuiConfigUILocalization.datatexthaste = "加速 (輸入 0 以停用)"
	TukuiConfigUILocalization.datatextfriends = "好友資訊 (輸入 0 以停用)"
	TukuiConfigUILocalization.datatextwowtime = "時間 (輸入 0 以停用)"
	TukuiConfigUILocalization.datatextgold = "金錢 (輸入 0 以停用)"
	TukuiConfigUILocalization.datatextdps_text = "每秒傷害 (輸入 0 以停用)"
	TukuiConfigUILocalization.datatextcrit = "致命 (輸入 0 以停用)"
	TukuiConfigUILocalization.datatextdur = "耐久值 (輸入 0 以停用)"
	TukuiConfigUILocalization.datatextcurrency = "兌換通貨 (輸入 0 以停用)"
	TukuiConfigUILocalization.datatextmicromenu = "微型選單 (輸入 0 以停用)"
	TukuiConfigUILocalization.datatexthit = "命中 (輸入 0 以停用)"
	TukuiConfigUILocalization.datatextmastery = "精通 (輸入 0 以停用)"
	TukuiConfigUILocalization.datatexttalent = "顯示天賦 (輸入 0 以停用)"
	TukuiConfigUILocalization.datatextcalltoarms = "戰爭的號角和地城 (輸入 0 以停用)"

	 
	-- unit frames
	TukuiConfigUILocalization.unitframes = "單位框架"
	TukuiConfigUILocalization.unitframescombatfeedback = "顯示戰鬥資訊於玩家及目標框架上"
	TukuiConfigUILocalization.unitframesrunebar = "啟用死亡騎士符文列"
	TukuiConfigUILocalization.unitframesauratimer = "在光環上顯示時間"
	TukuiConfigUILocalization.unitframestotembar = "啟用薩滿圖騰列"
	TukuiConfigUILocalization.unitframesshowtotalhpmp = "顯示總生命/能量值"
	TukuiConfigUILocalization.unitframesshowplayerinparty = "在隊伍中顯示自己"
	TukuiConfigUILocalization.unitframesraidunitdebuffwatch = "啟用PVE團隊光環監控 (Grid專用)"
	TukuiConfigUILocalization.unitframesunitcastbar = "啟用施法條"
	TukuiConfigUILocalization.unitframestargetauras = "啟用目標光環"
	TukuiConfigUILocalization.unitframessaveperchar = "依角色記錄單位框架位置"
	TukuiConfigUILocalization.unitframesplayeraggro = "啟用玩家仇恨顯示"
	TukuiConfigUILocalization.unitframesshowsmooth = "啟用狀態條動畫"
	TukuiConfigUILocalization.unitframescharportrait = "啟用玩家及目標框架的頭像"
	TukuiConfigUILocalization.unitframesenable = "啟用Tukui單位框架"
	TukuiConfigUILocalization.unitframestargetpowerpvponly = "只顯示敵對目標能量值"
	TukuiConfigUILocalization.unitframesgridonly = "啟用Grid治療限定介面"
	TukuiConfigUILocalization.unitframeshealcomm = "啟用即將到來的治療"
	TukuiConfigUILocalization.unitframesfocusdebuff = "啟用專注目標減益狀態"
	TukuiConfigUILocalization.unitframesaggro = "啟用隊伍/團隊仇恨顯示"
	TukuiConfigUILocalization.unitframesshowboss = "啟用首領單位框架"
	TukuiConfigUILocalization.unitframesenemyhcolor = "以敵對狀態將敵對目標的生命值上色 (PVP)"
	TukuiConfigUILocalization.unitframesgridhealthvertical = "Grid介面中生命值以垂直方向顯示"
	TukuiConfigUILocalization.unitframesshowsymbols = "顯示隊伍/團隊標記"
	TukuiConfigUILocalization.unitframesthreatbar = "啟用仇恨條"
	TukuiConfigUILocalization.unitframesshowrange = "啟用隊伍/團隊距離淡出"
	TukuiConfigUILocalization.unitframesfocus = "啟用專注目標"
	TukuiConfigUILocalization.unitframescblatency = "顯示施法延遲"
	TukuiConfigUILocalization.unitframescbicons = "顯示施法條法術圖示"
	TukuiConfigUILocalization.unitframesplayerauras = "在玩家上顯示另外的光環模式"
	TukuiConfigUILocalization.unitframesauratextscale = "光環上的文字大小"
	TukuiConfigUILocalization.unitframesgridscale = "Grid大小調整"
	TukuiConfigUILocalization.unitframesmanahigh = "法力過高警告(獵人專用)"
	TukuiConfigUILocalization.unitframeslowThreshold = "法力過低警告(所有有法力的職業)"
	TukuiConfigUILocalization.unitframesraidalphaoor = "隊伍/團隊單位超出距離透明值"
	TukuiConfigUILocalization.unitframesmaintank = "啟用主坦克框架"
	TukuiConfigUILocalization.unitframesmainassist = "啟用主助攻框架"
	TukuiConfigUILocalization.unitframesunicolor = "啟用特殊顏色樣式(灰色生命值)"
	TukuiConfigUILocalization.unitframestotdebuffs = "啟用目標的目標減益狀態(高解析度專用)"
	TukuiConfigUILocalization.unitframesclassbar = "啟用職業專用列"
	TukuiConfigUILocalization.unitframesweakenedsoulbar = "啟用虛弱靈魂指示 (牧師)"
	TukuiConfigUILocalization.unitframesonlyselfdebuffs = "目標頭像上只顯示自己施放的減益狀態"
	TukuiConfigUILocalization.unitframesshowfocustarget = "啟用專注目標的目標"
	TukuiConfigUILocalization.unitframesbordercolor = "設定單位框架的邊框顏色"
	TukuiConfigUILocalization.unitframesmovecombobar = "移動目標的連擊點條 (盜賊限定)"
	TukuiConfigUILocalization.unitframesclassiccombo = "使用經典連擊點樣式"
	TukuiConfigUILocalization.unitframesgridvertical = "Grid上的隊伍以垂直方向顯示"
	TukuiConfigUILocalization.unitframesraid = "Enable Tukui Raid Frames"
	TukuiConfigUILocalization.unitframesshowraidpets = "Show Pets in Tukui Raid Frames"
	TukuiConfigUILocalization.unitframesdruidmanabar = "Show Druid Mana Bar in Bear/Cat form"
	TukuiConfigUILocalization.unitframesdruidmushroombar = "Show Druid Mushroom bar in Balance or Restoration specialization"
	TukuiConfigUILocalization.unitframesmageclassbar = "Show Mage Arcane Bar"
	TukuiConfigUILocalization.unitframesraidunitspercolumn = "Number of raid units per column/row"
	TukuiConfigUILocalization.unitframesmaxraidplayers = "Max raid frames displayed according to instance max players"
	 
	-- loot
	TukuiConfigUILocalization.loot = "戰利品"
	TukuiConfigUILocalization.lootlootframe = "啟用戰利品視窗"
	TukuiConfigUILocalization.lootautogreed = "啟用自動貪婪物品(限用於最高等級)"
	TukuiConfigUILocalization.lootrolllootframe = "啟用骰裝視窗"
	 
	-- invite
	TukuiConfigUILocalization.invite = "邀請"
	TukuiConfigUILocalization.inviteautoaccept = "啟用自動接受組隊邀請及自動邀請(限用好友及公會成員)"
	 
	-- tooltip
	TukuiConfigUILocalization.tooltip = "提示資訊"
	TukuiConfigUILocalization.tooltipenable = "啟用提示資訊"
	TukuiConfigUILocalization.tooltiphidecombat = "戰鬥中隱藏指示資訊"
	TukuiConfigUILocalization.tooltiphidebuttons = "隱藏動作列按鍵提示資訊"
	TukuiConfigUILocalization.tooltiphideuf = "隱藏單位框架提示資訊"
	TukuiConfigUILocalization.tooltipcursor = "啟用滑鼠旁提示資訊"
	 
	-- error
	TukuiConfigUILocalization.error = "錯誤訊息"
	TukuiConfigUILocalization.errorenable = "隱藏畫面中間的錯誤訊息"
	 
	-- action bar
	TukuiConfigUILocalization.actionbar = "動作列"
	TukuiConfigUILocalization.actionbarhideshapeshift = "隱藏姿勢列及圖騰列"
	TukuiConfigUILocalization.actionbarshowgrid = "動作列上總是顯示方格"
	TukuiConfigUILocalization.actionbarenable = "啟用Tukui動作列"
	TukuiConfigUILocalization.actionbarrb = "啟用滑鼠移至右側動作列時才顯示"
	TukuiConfigUILocalization.actionbarhotkey = "顯示熱鍵文字"
	TukuiConfigUILocalization.actionbarssmo = "滑鼠移至姿勢列或圖騰列時才顯示"
	TukuiConfigUILocalization.actionbarrbn = "底部動作列列數(1 或 2)"
	TukuiConfigUILocalization.actionbarrn = "右側動作列列數 (0, 1, 2 或 3)"
	TukuiConfigUILocalization.actionbarbuttonsize = "動作列按鍵大小"
	TukuiConfigUILocalization.actionbarbuttonspacing = "動作列按鍵的間隔距離"
	TukuiConfigUILocalization.actionbarpetbuttonsize = "寵物或變形列按鍵大小"
	TukuiConfigUILocalization.actionbarownshdbar = "暗影之舞使用空白列而不是潛行列 (盜賊)"
	TukuiConfigUILocalization.actionbarownmetabar = "Use an empty bar for Metamorphosis (warlock) instead of main bar"
	TukuiConfigUILocalization.actionbarownwarstancebar = "Use an empty bar for each stance (warrior) instead of main bar"
	TukuiConfigUILocalization.actionbarmacro = "Show macro text on action bar"
	 
	-- arena
	TukuiConfigUILocalization.arena = "競技場"
	TukuiConfigUILocalization.unitframesarena = "啟用競技場單位框架"
	 
	-- cooldowns
	TukuiConfigUILocalization.cooldown = "冷卻"
	TukuiConfigUILocalization.cooldownenable = "啟用按鍵冷卻倒數"
	TukuiConfigUILocalization.cooldowntreshold = "冷卻小於X秒倒數以紅字顯示"
	 
	-- chat
	TukuiConfigUILocalization.chat = "聊天"
	TukuiConfigUILocalization.chatenable = "啟用Tukui對話框"
	TukuiConfigUILocalization.chatwhispersound = "收到悄悄話時以音效提醒"
	TukuiConfigUILocalization.chatbackground = "啟用對話框背景"

	-- buff
	TukuiConfigUILocalization.auras = "光環"
	TukuiConfigUILocalization.aurasplayer = "啟用Tukui增/減益狀態框架"
	TukuiConfigUILocalization.aurasconsolidate = "合併增益狀態"
	TukuiConfigUILocalization.aurasflash = "光環少於30秒時以閃動動畫顯示"
	TukuiConfigUILocalization.aurasclassictimer = "Display classic timer on player auras"

	-- buttons
	TukuiConfigUILocalization.option_button_reset = "重置"
	TukuiConfigUILocalization.option_button_load = "套用設定"
	TukuiConfigUILocalization.option_button_close = "關閉"
	TukuiConfigUILocalization.option_setsavedsetttings = "依角色儲存設定"
	TukuiConfigUILocalization.option_resetchar = "你確定要將你的角色設定回復到預設設定嗎?"
	TukuiConfigUILocalization.option_resetall = "你確定要將你所有的設定回復到系統預設值嗎?"
	TukuiConfigUILocalization.option_perchar = "你確定要啟用或者關閉依角色儲存設定的模式嗎?"
	TukuiConfigUILocalization.option_makeselection = "你必須作出選擇才能繼續設定"
end